COURSE.add({id:'s03',n:3,part:'A',track:'HLD',
title:'Storage: data modelling, indexes and transactions',
goal:'Model data, make reads fast with indexes, protect writes with transactions, and choose between SQL and NoSQL.',
outcomes:['Turn requirements into tables and keys','Explain how an index turns a scan into a lookup','Use transactions and isolation to stop races','Pick a storage type for a workload and defend it'],
concept:'storage',
tasks:[{t:'Model a library: tables, keys and the index for each hot query.'},{t:'Diagnose the slow query: index, cache or shard?',auto:'s03slow'},{t:'Choose SQL or NoSQL for 8 products and justify each choice.',auto:'s03db'},{t:'Explain why large files go to object storage, using the upload diagram.',auto:'s03obj'},{t:'Answer the storage interview checkpoint.',auto:'s03cp'},{t:'Rate yourself: can you choose storage for a workload without notes?',auto:'s03sum'}],
modules:[
{title:'Warm-up: recall session 2',tab:'Warm-up',mins:10,out:'Recall quiz',blocks:[
 {t:'mcq',items:[
  {q:'Which pagination survives new inserts without duplicates?',opts:['Offset','Cursor'],a:1},
  {q:'How do you make POST /payments safe to retry?',opts:['Use PUT instead','Idempotency key','Longer timeout'],a:1},
  {q:'Best style for service-to-service calls at high volume?',opts:['gRPC','GraphQL','WebSocket'],a:0}]}]},

{title:'Data modelling',tab:'Modelling',mins:30,out:'A library data model',lead:'Start from the nouns in the requirements, then decide the keys and the relationships. The most frequent query decides the shape.',blocks:[
 {t:'grid',title:'The three relationships',items:[
  {title:'One-to-one',body:'User ↔ Profile. Often the same table, or a separate table sharing the key.'},
  {title:'One-to-many',body:'Author → Books. The "many" side holds a foreign key (<code>book.author_id</code>).'},
  {title:'Many-to-many',body:'Students ↔ Courses. A join table <code>enrollment(student_id, course_id)</code>.'}]},
 {t:'grid',cols:2,title:'Normalise or denormalise?',items:[
  {tag:'Normalised',title:'Each fact stored once',body:'Updates are simple and consistent. Reads may need joins. Default for transactional data (orders, payments).'},
  {tag:'Denormalised',tc:'amber',title:'Copies for fast reads',body:'Store <code>author_name</code> inside each post so the feed needs no join. Reads are fast; updates must change every copy. Common in read-heavy and NoSQL systems.'}]},
 {t:'stepper',title:'Exercise · Model a library',steps:[
  {title:'Nouns',secs:90,think:'Requirements: members borrow copies of books; a book can have many copies; members can reserve a book; we keep loan history. List the entities.',answer:'Member, Book (title, ISBN), Copy (a physical item of a Book), Loan, Reservation.'},
  {title:'Keys and relations',short:'Relations',secs:150,think:'Write the tables with primary and foreign keys.',answer:'<pre>member(id PK, name, email UNIQUE)\nbook(isbn PK, title, author)\ncopy(id PK, isbn FK→book, branch, status)\nloan(id PK, copy_id FK, member_id FK, out_at, due_at, returned_at)\nreservation(id PK, isbn FK, member_id FK, created_at, status)</pre><p>Reservations point at the <b>book</b>, not a copy: any copy can satisfy them.</p>'},
  {title:'Hot queries',short:'Queries',secs:120,think:'Name the two most frequent queries and the index each needs.',answer:'<ul class="clean"><li>"My current loans": <code>loan WHERE member_id=? AND returned_at IS NULL</code> → index on (member_id, returned_at).</li><li>"Is any copy free?": <code>copy WHERE isbn=? AND status=\'available\'</code> → index on (isbn, status).</li></ul>'}]}]},

{title:'Indexes: from scan to lookup',tab:'Indexes',mins:30,out:'Explain an index with numbers',lead:'Without an index the database reads every row. A B-tree index keeps keys sorted in a shallow tree, so a lookup touches a handful of pages.',blocks:[
 {t:'lab',fn:'index',title:'Lab · Full scan vs B-tree lookup'},
 {t:'table',title:'Index facts that come up in interviews',head:['Fact','Why it matters'],rows:[
  ['Indexes speed reads but slow writes','Every insert also updates each index'],
  ['Composite index (a, b) helps queries on a, or a+b','But not queries on b alone: the leftmost-prefix rule'],
  ['Range queries work on B-trees','<code>created_at BETWEEN …</code>; hash indexes only do equality'],
  ['A covering index holds all needed columns','The query never touches the table'],
  ['Low-selectivity columns (gender) index poorly','Most rows match, so a scan is similar']]},
 {t:'mcq',title:'Leftmost prefix',intro:'Index on <code>(country, city, created_at)</code>. Can the index be used?',items:[
  {q:'<code>WHERE country=\'IN\' AND city=\'Pune\'</code>',opts:['Yes','No'],a:0,why:'Uses the first two columns in order.'},
  {q:'<code>WHERE city=\'Pune\'</code>',opts:['Yes','No'],a:1,why:'Skips the first column, so the sorted order does not help.'},
  {q:'<code>WHERE country=\'IN\' ORDER BY city</code>',opts:['Yes','No'],a:0,why:'Rows for IN are already sorted by city inside the index.'}]},
 {t:'predict',id:'s03slow',kind:'bottleneck',title:'Where is the bottleneck?',level:'f',scenario:'"My orders" takes 3 s. The <code>orders</code> table has 50 M rows; the query is <code>WHERE user_id = ? ORDER BY created_at DESC LIMIT 20</code>.',metrics:[['DB CPU','90%','bad'],['Rows examined per query','50,000,000','bad'],['Rows returned','20','ok'],['API CPU','25%','ok'],['Cache','none','']],q:'What would you change first?',
  opts:[['Add an index on (user_id, created_at)',1,'The database scans 50 M rows to return 20. A composite index turns that into a handful of page reads.'],['Add a Redis cache',0,'Caching hides a missing index and still runs the 3 s query on every miss.'],['Shard the orders table',0,'Splitting the table makes each scan smaller but keeps scanning. An index is the cheap, correct fix.'],['Add read replicas',0,'Each replica would run the same full scan.']],
  takeaway:'Measure rows examined vs rows returned. When they differ by orders of magnitude, the fix is an index, not more machines.'}]},

{title:'Transactions and isolation',tab:'Transactions',mins:25,out:'Explain a race and its fix',lead:'A transaction groups writes so they all happen or none do. Isolation decides what concurrent transactions can see of each other.',blocks:[
 {t:'cards',title:'ACID',items:[
  {tag:'A',title:'Atomicity',body:'All or nothing. Debit and credit both happen, or neither.'},
  {tag:'C',title:'Consistency',body:'Rules (constraints, foreign keys) hold before and after.'},
  {tag:'I',title:'Isolation',body:'Concurrent transactions do not see each other\'s half-done work (to a chosen level).'},
  {tag:'D',title:'Durability',body:'Once committed, it survives a crash (written to the log on disk).'}]},
 {t:'table',title:'What can go wrong without enough isolation',head:['Anomaly','What happens','Prevented by'],rows:[
  ['Dirty read','You read another transaction\'s uncommitted change','Read committed'],
  ['Non-repeatable read','Same row read twice gives different values','Repeatable read / snapshot'],
  ['Lost update','Two read-modify-writes; one overwrites the other','Row locks, <code>SELECT … FOR UPDATE</code>, atomic updates, version checks'],
  ['Write skew / double booking','Two transactions each check a rule, both write','Serializable, or a unique constraint / conditional update']]},
 {t:'lab',fn:'seatRace',title:'Lab · Two buyers, one seat',intro:'Run the naive version, find the bug, then run the conditional update.'},
 {t:'teacher',items:['After the lab, show the three common fixes: conditional update (<code>WHERE status=\'available\'</code>), row lock (<code>FOR UPDATE</code>), unique constraint on (event, seat) in a bookings table.']}]},

{title:'SQL or NoSQL? Choosing storage',tab:'Choosing storage',mins:25,out:'Storage choice per workload',blocks:[
 {t:'grid',title:'Storage families',items:[
  {tag:'Relational',title:'PostgreSQL, MySQL',body:'Tables, joins, transactions. Default for business data with relations.'},
  {tag:'Key-value',title:'Redis, DynamoDB',body:'Get/put by key, very fast. Sessions, carts, counters, caches.'},
  {tag:'Document',title:'MongoDB',body:'JSON documents with varying shape. Product catalogues, profiles.'},
  {tag:'Wide-column',title:'Cassandra, HBase',body:'Huge write volumes, query by partition key. Messages, time series, logs.'},
  {tag:'Search',title:'Elasticsearch',body:'Full-text search and filters. Kept in sync from the main database.'},
  {tag:'Object storage',title:'S3-style blobs',body:'Images, video, backups. Cheap, huge, accessed by key via URL/CDN.'}]},
 {t:'mcq',title:'Pick the storage',items:[
  {q:'Bank accounts and transfers',opts:['Relational','Wide-column','Object storage'],a:0,why:'Transactions and constraints matter most.'},
  {q:'Chat messages: 50 K writes/s, read by conversation',opts:['Relational, one server','Wide-column partitioned by conversation','Search engine'],a:1,why:'High write volume, simple access by partition key.'},
  {q:'User-uploaded videos',opts:['Relational BLOB column','Object storage + metadata in a DB','Key-value cache'],a:1,why:'Large files belong in object storage behind a CDN.'},
  {q:'"Search products by any word in the description"',opts:['LIKE \'%word%\' in SQL','Search index','Key-value'],a:1,why:'Inverted indexes make full-text search fast.'},
  {q:'Shopping cart for a logged-in user',opts:['Key-value','Graph database','Object storage'],a:0,why:'One key (user) → small value, read and written often.'}]},
 {t:'flash',title:'Review flashcards',items:[['Why not index every column?','Each index slows writes and uses space.'],['Lost update fix?','Atomic update, row lock, or version check (optimistic locking).'],['When denormalise?','Read-heavy paths where joins are too slow; accept harder updates.'],['Where do images go?','Object storage + CDN; the DB stores the URL.'],['Wide-column store is good for…','Very high write volume read by a partition key.'],['Composite index rule?','Leftmost prefix: (a,b) helps a and a+b, not b alone.']]},
 {t:'task',title:'Homework',items:['Model the data for a cinema booking system: tables, keys, two hot queries and their indexes.']},
 {t:'decide',id:'s03db',title:'Decision lab · SQL or NoSQL?',level:'i',intro:'Choose, then tick the reasons that drove your choice. Several answers can be defended; the reasoning is what is graded.',ask:'SQL or NoSQL?',items:[
  {short:'Instagram comments',q:'We are designing <b>Instagram comments</b>: billions of comments, read by post, newest first; a comment rarely changes.',opts:['Relational (SQL)','Wide-column NoSQL'],a:[1,0],reasons:[['Access is always "comments for post X, newest first"',1],['Write volume is huge and grows without bound',1],['We need multi-row transactions across comments',0],['Comments have complex joins with many tables',0]],explain:'A wide-column store partitioned by post_id, clustered by time, fits the single access pattern and scales writes. SQL with sharding by post_id also works; say what you give up (operational cost vs. flexible queries).',whyNot:'A single relational server cannot hold billions of rows of writes; you would shard it, which is fine but more work.'},
  {short:'Payments',q:'A <b>payment system</b>: debit one account, credit another, never lose or duplicate money.',opts:['Relational (SQL)','Key-value NoSQL'],a:0,reasons:[['Atomic multi-row transactions are essential',1],['Strong consistency and constraints matter more than raw scale',1],['The schema changes every week',0],['Reads are 1,000× writes',0]],explain:'ACID transactions, constraints and a ledger table make SQL the default. Scale with partitioning by account later.',whyNot:'Most key-value stores trade multi-key transactions for scale; reproducing them in the application is error-prone.'},
  {short:'Chat messages',q:'<b>Chat messages</b>: 50 K writes/s, read by conversation, kept for years.',opts:['Relational (SQL)','Wide-column NoSQL'],a:1,reasons:[['Very high write throughput',1],['Read pattern is "messages in conversation X by time"',1],['Complex reporting joins are required on the hot path',0],['Data volume grows forever',1]],explain:'Partition by conversation_id, cluster by message time. Writes spread across nodes and reads hit one partition.',whyNot:'SQL can work sharded by conversation, but you would be rebuilding what a wide-column store gives you.'},
  {short:'Product catalogue',q:'A <b>product catalogue</b>: each category has different attributes (shoes have sizes, laptops have CPUs).',opts:['Relational (SQL)','Document NoSQL'],a:[1,0],reasons:[['Attributes vary a lot per product type',1],['Products are read as one whole document',1],['Inventory updates need transactions with orders',0],['We need full-text search inside descriptions',0]],explain:'A document store holds each product with its own shape. SQL with a JSON column is also a strong answer. Search goes to a search index either way.',whyNot:'Pure relational tables with a column per attribute become sparse and hard to change.'},
  {short:'Analytics events',q:'<b>Analytics events</b>: 200 K clicks per second, appended once, queried in bulk by time.',opts:['Relational (SQL)','Log/columnar store (Kafka → warehouse)'],a:1,reasons:[['Append-only, never updated',1],['Queries scan large time ranges',1],['Each event must join with user records in real time',0],['Write rate is far beyond one database',1]],explain:'Stream events into a log (Kafka), then a columnar warehouse or time-series store for scans and aggregates.',whyNot:'Row-oriented OLTP databases are poor at both huge append rates and big scans.'},
  {short:'Social graph',q:'A <b>social graph</b>: who follows whom, "friends of friends", mutual followers.',opts:['Relational (SQL)','Graph or adjacency lists in KV'],a:[0,1],reasons:[['Queries traverse relationships several hops deep',1],['The main read is "followers of X"',1],['Each edge is written once and rarely changed',0],['We need ad-hoc reporting',0]],explain:'Most products store adjacency lists (follower/followee tables, sharded by user) because the hot query is one hop. Graph databases shine for multi-hop traversals.',whyNot:'Deep traversals in SQL need recursive joins that get slow.'},
  {short:'URL shortener',q:'A <b>URL shortener</b>: code → long URL, 100:1 reads, billions of rows.',opts:['Relational (SQL)','Key-value NoSQL'],a:[0,1],reasons:[['Single access pattern: lookup by key',1],['Read-heavy and cacheable',1],['Multi-table transactions',0],['Joins between links and users on every redirect',0]],explain:'Either works. A key-value store matches the access pattern and scales horizontally; SQL with a cache is simpler at moderate scale.',whyNot:'The choice matters less than caching the hot codes.'},
  {short:'Session store',q:'A <b>session store</b>: lookup by session id on every request, expires after 30 minutes.',opts:['Relational (SQL)','In-memory key-value (Redis)'],a:1,reasons:[['Sub-millisecond reads on every request',1],['Data naturally expires (TTL)',1],['Losing a session is tolerable (re-login)',1],['Needs complex queries',0]],explain:'Redis with TTLs: fast, simple, expiring. Replicate it so a node failure does not log everyone out.',whyNot:'A relational table works but adds load on the database for every request.'},
  {short:'Search index',q:'"Search products by any word in the title or description."',opts:['SQL LIKE queries','Search engine (inverted index)'],a:1,reasons:[['Full-text matching and relevance ranking',1],['Typo tolerance and filters',1],['It must be the source of truth',0],['Queries are exact key lookups',0]],explain:'An inverted index (Elasticsearch/OpenSearch) built from the main database. The database stays the source of truth.',whyNot:'<code>LIKE \'%word%\'</code> cannot use a B-tree index and scans every row.'}]},
 {t:'diagram',id:'s03obj',title:'Diagram · Large files: object storage with direct upload',intro:'Large files never pass through your database, and ideally not through your API servers either.',nodes:['client@0,1:Client','api@1,1:API servers','db@2,1:Database|metadata','obj@2,0:Object storage|the bytes','cdn@1,0:CDN'],edges:['client>api:1. ask to upload','api>db:metadata','client>obj:3. PUT signed URL','cdn~>obj:origin','client>cdn:5. view'],
  steps:[{hi:['client','api'],txt:'The client asks to upload a 20 MB photo.'},{hi:['api','db'],txt:'The API creates a metadata row (id, owner, size, status=pending) and returns a short-lived <b>signed URL</b>.'},{hi:['client','obj'],txt:'The client uploads the bytes straight to object storage. Your servers never carry them.'},{hi:['api','db'],txt:'An upload-complete event marks the row as ready (and can trigger thumbnails via a queue).'},{hi:['client','cdn','obj'],txt:'Viewers fetch the photo from the CDN, which pulls it from object storage once.'}]},
 {t:'diagram',title:'Diagram · Search architecture',nodes:['api@0,1:API servers','db@1,1:Database|source of truth','kafka@2,1:Change stream|CDC / events','worker@3,1:Indexer','search@3,0:Search index','api2@2,0:Search API'],edges:['api>db:writes','db>kafka:changes','kafka>worker','worker>search','api2>search:queries'],caption:'Writes go to the database; a change stream feeds an indexer that updates the search index. Search results can lag writes by seconds: eventual consistency.'},
 {t:'checkpoint',id:'s03cp',title:'Interview checkpoint',prompt:'"How would you store data for an e-commerce site: users, products, orders, product images and search?"',steps:['List entities and their relationships','Name the hot reads and the riskiest write','Pick storage per data type, with a reason','Design keys and indexes for the hot queries','Protect the riskiest write (stock decrement) with a transaction/conditional update','Keep large files out of the database','Keep search in sync and accept lag','Mention scale triggers (replicas, partitioning)'],
  model:'Users, orders, inventory → PostgreSQL (transactions; index orders(user_id, created_at)). Catalogue → document store or JSONB. Images → object storage + CDN, URLs in the DB. Search → inverted index fed by CDC. Checkout: conditional update on stock in one transaction.',followups:[['"Stock goes negative during a flash sale."','<code>UPDATE stock SET qty=qty-1 WHERE sku=? AND qty>0</code>; check affected rows.'],['"Search shows a product that was just deleted."','Index lag. Filter by a fresh availability check on click, and propagate deletes with priority.']]},
 {t:'recall',title:'Active recall',items:[['What does an index trade?','Faster reads for slower writes and extra storage; every insert updates every index.'],['What is the leftmost-prefix rule?','An index on (a, b) helps queries on a or a+b, not on b alone.'],['What anomaly causes double booking?','Write skew / lost update: two transactions check, then both write. Fix with a conditional update, lock or unique constraint.'],['When would you choose a wide-column store?','Huge write volume with access by a partition key (messages, time series).'],['Where do videos and images go?','Object storage behind a CDN; the database keeps only metadata.']]},
 {t:'summary',id:'s03sum',title:'Session summary',learned:['<b>Why indexes exist:</b> turn full scans into lookups','<b>When to use SQL:</b> relations, transactions, constraints','<b>When to use NoSQL:</b> one dominant access pattern at huge scale, flexible shapes, TTL data','<b>Trade-offs:</b> normalise vs denormalise, consistency vs scale','<b>Interview questions:</b> data model, hot queries, storage choice, race conditions'],explain:'Pick storage for chat messages, payments and product images, and defend each choice in one sentence.'}]}
],
labs:{
 index(el,api){
  el.innerHTML=`<label>Rows in table: <b data-n></b><input type="range" min="3" max="9" step="1" value="6" data-r></label><div class="out"><div><b data-scan></b><span>rows read by a full scan (worst case)</span></div><div><b data-depth></b><span>B-tree levels (≈ 200 keys per page)</span></div><div><b data-look></b><span>pages read with the index</span></div><div><b data-x></b><span>times less work</span></div></div><div class="verdict" data-v></div>`;
  const draw=()=>{const p=+api.$('[data-r]',el).value,n=Math.pow(10,p);const depth=Math.max(1,Math.ceil(Math.log(n)/Math.log(200)));
   api.$('[data-n]',el).textContent=n.toLocaleString();api.$('[data-scan]',el).textContent=n.toLocaleString();api.$('[data-depth]',el).textContent=depth;api.$('[data-look]',el).textContent=depth+1;api.$('[data-x]',el).textContent=Math.round(n/(depth+1)).toLocaleString()+'x';
   api.$('[data-v]',el).innerHTML=`Growing the table 1,000x adds only about one level to the tree. That is why <code>WHERE email = ?</code> stays fast at a billion rows, as long as <code>email</code> is indexed.`};
  el.addEventListener('input',draw);draw()}
}});
