COURSE.add({id:'s04',n:4,part:'A',track:'HLD',
title:'Caching and CDNs',
goal:'Make reads fast and cheap with caches, and handle the hard parts: invalidation, stampedes and hot keys.',
outcomes:['Place caches at the right layer','Choose cache-aside, write-through or write-back','Predict hit rate from capacity and traffic skew','Handle stale data, stampedes and hot keys'],
concept:'caching',
tasks:[{t:'Explain why a cache helps a read-heavy, skewed workload, using the "80% of requests hit 5% of data" numbers.'},{t:'Predict each step of the architecture evolution before revealing it.',auto:'s04evolve'},{t:'Complete the cache lab: hit, miss, TTL, stale read, invalidation, stampede.',auto:'s04cache'},{t:'Estimate the cache size for a 10 M DAU app.',auto:'s04cap'},{t:'Scale the product page to 10K req/s, diagnosing the bottleneck first.',auto:'s04scale'},{t:'Answer the interview checkpoint before reading the reference.',auto:'s04cp'},{t:'Rate yourself: can you explain cache-aside without notes?',auto:'s04sum'}],
modules:[
{title:'Warm-up: recall session 3',tab:'Warm-up',mins:10,out:'Recall quiz',blocks:[
 {t:'mcq',items:[
  {q:'Index on (a, b). Does <code>WHERE b = 5</code> use it?',opts:['Yes','No'],a:1},
  {q:'Where do user videos go?',opts:['Relational table','Object storage + CDN'],a:1},
  {q:'Two buyers grab one seat. Simplest correct fix?',opts:['Read then write','Conditional update / row lock','Retry later'],a:1}]}]},

{title:'Why and where to cache',tab:'Where to cache',mins:20,out:'Name 5 cache layers',lead:'A cache keeps a copy of data closer to the reader. It trades memory and freshness for speed and lower load.',blocks:[
 {t:'cards',title:'Cache layers, from the user inward',items:[
  {tag:'Layer 1',title:'Browser / app',sub:'Cache-Control headers',body:'<p>Static files and some API responses cached on the device. Zero network cost. Control with <code>Cache-Control: max-age=…</code> and ETags.</p>'},
  {tag:'Layer 2',title:'CDN edge',sub:'Near the user',body:'<p>Servers in many cities hold images, video, JS and cacheable pages. Cuts latency from ~150 ms to ~20 ms and takes most bandwidth off your servers.</p><p><b>Push</b> CDN: you upload. <b>Pull</b> CDN: fetches from your origin on first miss.</p>'},
  {tag:'Layer 3',title:'Application memory',sub:'Per server',body:'<p>A small in-process cache (config, hot lookups). Fastest, but each server has its own copy, so they can disagree.</p>'},
  {tag:'Layer 4',title:'Distributed cache',sub:'Redis / Memcached',body:'<p>A shared cache cluster that all app servers use. The usual answer for "add a cache" in interviews. Sub-millisecond reads.</p>'},
  {tag:'Layer 5',title:'Database buffer',sub:'Inside the DB',body:'<p>The database keeps hot pages in memory itself. Free, but limited by the DB machine\'s RAM.</p>'}]},
 {t:'grid',cols:2,title:'When caching helps, and when it does not',items:[
  {tag:'Helps',tc:'green',title:'Read-heavy, skewed, tolerant',body:'Many more reads than writes; a small set of items gets most reads; readers accept data a few seconds old.'},
  {tag:'Hurts',tc:'red',title:'Write-heavy, uniform, strict',body:'Every item read once; data changes constantly; readers must always see the latest value (account balance at checkout).'}]},
 {t:'predict',title:'What happens next?',level:'f',scenario:'A product page takes <b>400 ms</b>. Measurements show <b>80% of requests</b> repeatedly read the same <b>5% of products</b>, and product details change a few times a day.',metrics:[['p50 latency','400 ms','bad'],['DB CPU','85%','warn'],['API CPU','30%','ok'],['Reads : writes','200 : 1','']],q:'Would caching help here?',
  opts:[['Yes: a small hot set, read often, rarely changed',1,'Caching 5% of products in memory can serve ~80%+ of reads in ~1 ms, so the database drops from 85% CPU and latency falls from 400 ms to a few ms for hits.'],['No: caches only help static files',0,'Distributed caches (Redis, Memcached) hold API data too, not just files.'],['No: we should shard the database instead',0,'Sharding splits data and writes. The problem is the same few rows read again and again: a cache is far cheaper.'],['Only if we also add API servers',0,'API CPU is 30%: it is not the bottleneck.']],
  takeaway:'Caching pays off when reads dominate, a small set is hot, and slightly stale data is acceptable.'},
 {t:'evolve',id:'s04evolve',title:'Diagram · How a product page grows, one problem at a time',intro:'Each stage exists because the previous design failed on a measured problem. Predict the change before you reveal it.',stages:[
  {label:'Day one',nodes:['client@0,1','api@1,1:API servers','db@2,1:PostgreSQL|every read'],edges:['client>api','api>db'],
   problem:'None yet. A few hundred requests per second; the database answers every read.',fix:'The simplest design that works: stateless API servers and one database.'},
  {label:'Add Redis',nodes:['client@0,1','api@1,1:API servers','cache@2,0:Redis|hot products','db@2,1:PostgreSQL|misses only'],edges:['client>api','api>cache:1. GET','api>db:2. on miss'],
   predict:{q:'Traffic grew 10×. DB CPU is 92%, API CPU 34%, and 80% of reads hit 5% of products. What do you change first?',opts:[['Add a cache for the hot products',1,'Correct target: the DB is saturated by repeated reads of a small hot set.'],['Add API servers',0,'API CPU is 34%. More servers would add more load on the database.'],['Shard the database',0,'Sharding helps write volume and data size. Here the same rows are read repeatedly: premature.'],['Add Kafka',0,'A queue moves slow work out of the request path; these are reads that need an answer now.']]},
   problem:'The database re-reads the same rows thousands of times a second and is at 92% CPU.',fails:'Every request pays the full database cost, even for data that changed hours ago.',fix:'Redis with cache-aside: read Redis; on a miss read the database and store the value with a TTL.',introduces:'Stale data until the TTL or an invalidation; stampedes when a hot key expires; an empty cache after a restart; one more system to operate.',
   whyNot:[['Why not read replicas?','They also scale reads, but every read still runs a query and replicas lag. For a tiny hot set, memory is cheaper and ~10× faster per read.'],['Why not shard now?','Sharding adds routing, rebalancing and cross-shard queries, and does nothing for one hot key. Premature while a cache solves the bottleneck.']]},
  {label:'Add a CDN',nodes:['client@0,1','cdn@1,0:CDN|images · JS · CSS','api@1,1:API servers','cache@2,0:Redis|hot products','db@2,1:PostgreSQL|misses only'],edges:['client>cdn','client>api','api>cache:1. GET','api>db:2. on miss'],
   predict:{q:'API responses now take 15 ms, but users on another continent wait ~900 ms for the page, and image bandwidth is most of the bill. Next?',opts:[['Serve images and static files from a CDN',1,'Distance and bytes are the problem. Edges near users cut round trips and take the bandwidth off your servers.'],['A bigger Redis cluster',0,'Redis is not slow; the bytes travel far.'],['More API servers',0,'Static files should not go through API servers at all.']]},
   problem:'Images and scripts are most of the bytes, and every far-away user pays ~150 ms per round trip.',fails:'Redis speeds up the data lookup but not the trip across the world.',fix:'A CDN caches static files at edges near users, with versioned file names and long TTLs.',introduces:'Purging and invalidation, cost per GB, and personalised responses cannot be cached at the edge.'},
  {label:'Protect the hot key',nodes:['client@0,1','cdn@1,0:CDN|images · JS · CSS','api@1,1:API servers|+ 2 s local copy','cache@2,0:Redis cluster|key replicated ×3','db@2,1:PostgreSQL|misses only'],edges:['client>cdn','client>api','api>cache:1. GET','api>db:2. single-flight'],
   predict:{q:'A flash sale makes one product 100× hotter. The Redis node holding it is at 95% CPU while the other nodes idle. Next?',opts:[['Short in-process copy on each API server + replicate the hot key',1,'One key lives on one node. Copies spread the load; a 1–2 s local cache removes most network calls.'],['Add more Redis nodes',0,'A single key still maps to a single node, so it stays hot.'],['Remove the TTL so it never expires',0,'Avoids expiry stampedes but keeps serving stale prices forever.']]},
   problem:'One key gets a huge share of traffic and melts one cache node.',fails:'Adding cache nodes spreads different keys, not one key.',fix:'Replicate the hot key (product:42#1..#3) and keep a 1–2 s local copy in each API server; single-flight rebuilds on a miss.',introduces:'Servers may show slightly different values for a second or two; more memory per server.'}]}
]},

{title:'Caching patterns',tab:'Patterns',mins:25,out:'Pick a pattern per scenario',blocks:[
 {t:'table',title:'Read and write patterns',head:['Pattern','How it works','Good','Cost'],rows:[
  ['Cache-aside (lazy)','App reads cache; on miss reads DB and fills cache','Simple; only caches what is read','First read is slow; stale until TTL or delete'],
  ['Read-through','Cache itself loads from DB on miss','App code is simpler','Cache must know the DB'],
  ['Write-through','Write cache and DB together','Cache always fresh','Slower writes; caches data never read'],
  ['Write-back (write-behind)','Write cache now, DB later in batches','Very fast writes','Data loss if the cache dies before flushing'],
  ['Write-around','Write DB only; cache fills on read','Avoids caching write-once data','Recent writes miss the cache']]},
 {t:'diagram',id:'s04trace',title:'Diagram · Trace cache-aside: a hit, then a miss',nodes:['client@0,1','api@1,1:API server|cache-aside','cache@2,0:Redis|product:42','db@2,1:PostgreSQL|source of truth'],edges:['client>api','api>cache:GET / SET','api>db:on miss'],
  steps:[{hi:['client','api'],txt:'<code>GET /products/42</code> reaches an API server.'},{hi:['api','cache'],txt:'The API asks Redis for <code>product:42</code> (~0.5 ms).'},{hi:['api','cache'],states:{cache:'ok'},txt:'<b>Hit.</b> Redis has it: return it. The database is never touched.'},{hi:['api','cache'],states:{cache:'warn'},txt:'Five minutes later the TTL has expired. <b>Miss.</b>'},{hi:['api','db'],txt:'The API queries PostgreSQL (~5 ms, or far more under load).'},{hi:['api','cache'],txt:'The API stores the row in Redis with <code>ttl=300</code>.'},{hi:['client','api'],txt:'The response returns. The next reads are hits until the TTL ends or a write deletes the key.'}]},
 {t:'diagram',title:'Diagram · Write-back: fast writes, risk of loss',nodes:['client@0,1','api@1,1:API server','cache@2,0:Redis|holds new value','db@2,1:Database|updated later'],edges:['client>api','api>cache:1. write now','cache~>db:2. flush in batches'],
  steps:[{hi:['client','api','cache'],txt:'A like is written to Redis only and acknowledged in ~1 ms.'},{hi:['cache','db'],txt:'Every few seconds a job flushes counters to the database in one batch: 50 K writes/s become a few hundred.'},{hi:['cache'],states:{cache:'down'},txt:'If Redis dies before the flush, the unflushed likes are lost. Acceptable for likes; never for payments.'}]},
 {t:'code',title:'Cache-aside in 10 lines',code:`
def get_product(pid):
    key = f"product:{pid}"
    cached = cache.get(key)
    if cached is not None:
        return cached                      # hit: ~0.5 ms
    product = db.query("SELECT * FROM products WHERE id = %s", pid)   # miss: ~5 ms
    cache.set(key, product, ttl=300)       # keep 5 minutes
    return product

def update_product(pid, fields):
    db.update("products", pid, fields)
    cache.delete(f"product:{pid}")         # delete, don't set: avoids racing writers`},
 {t:'mcq',title:'Which pattern?',items:[
  {q:'Product pages: read 1,000x more than edited; a minute of staleness is fine.',opts:['Cache-aside with TTL','Write-back','No cache'],a:0},
  {q:'Like counters updated 50 K times a second; losing a few likes on a crash is acceptable.',opts:['Write-through','Write-back (batch to DB)','Write-around'],a:1},
  {q:'Audit logs written once, almost never read.',opts:['Write-through','Write-around (do not cache)','Read-through'],a:1},
  {q:'Account balance shown at payment confirmation.',opts:['Cache with 5-minute TTL','Read from the database','CDN'],a:1,why:'Correctness beats speed here.'}]},
 {t:'compare',title:'Exercise · Which architecture for which data?',intro:'Same two designs, different data. Choose per scenario.',options:[{name:'Database only',nodes:['client@0,0:Client','api@1,0:API','db@2,0:DB'],edges:['client>api','api>db'],note:'Always current; every read costs a query.'},{name:'Cache in front',nodes:['client@0,0:Client','api@1,0:API','cache@2,0:Redis','db@3,0:DB'],edges:['client>api','api>cache','cache-db'],note:'Fast reads; data may be seconds old.'}],
  items:[{q:'a bank balance shown before a transfer',a:0,why:'Must be exact; showing an old balance can let a customer overspend. Read from the primary database.'},{q:'trending posts',a:1,why:'Read constantly, the same for everyone, and a minute of staleness is fine.'},{q:'user sessions',a:1,why:'Read on every request by key; Redis (often as the primary store) gives sub-ms lookups. Sessions expire, so TTLs fit naturally.'},{q:'product inventory at checkout',a:0,why:'Show "in stock" from cache on the page, but decrement stock in the database with a conditional update at checkout.'}]}]},

{title:'Lab: hit rate, capacity and skew',tab:'Lab',mins:25,out:'Explain hit rate with numbers',lead:'Hit rate depends on how much you cache and how skewed traffic is. Run the simulation and watch database load change.',blocks:[
 {t:'cachesim',id:'s04cache',title:'Lab · One hot key: hit, miss, TTL, stale data, stampede',level:'i',intro:'The database takes 400 ms per query; Redis takes 2 ms. Work through the experiments list; each ticks when you see it happen.'},
 {t:'capacity',id:'s04cap',title:'Capacity lab · How big must the cache be?',level:'f',intro:'Calculate first, then check. Cache size uses the 80/20 rule: keep the hottest 20% of a day\'s reads in memory.',scenarios:[{name:'Product catalogue',dau:10e6,rpu:20,ratio:100,obj:2000,peak:3},{name:'News site on election night',dau:30e6,rpu:10,ratio:500,obj:5000,peak:4}],ask:['reqDay','qps','peak','cache']},
 {t:'lab',fn:'lru'},
 {t:'teacher',items:['Set skew to "uniform" and show that even a large cache barely helps. Then set "very skewed": a 5% cache serves most reads.','Ask: "Why might LRU beat FIFO?" Popular items keep getting refreshed in LRU; FIFO evicts them on schedule.']}]},

{title:'The hard parts',tab:'Hard parts',mins:20,out:'Fixes for 4 cache problems',blocks:[
 {t:'grid',title:'Four problems and their fixes',items:[
  {tag:'Stale data',tc:'amber',title:'Cache disagrees with DB',body:'Use a TTL as a safety net; delete the key on write; for strict data, skip the cache. Order matters: update DB, then delete cache.'},
  {tag:'Stampede',tc:'red',title:'A hot key expires',body:'Thousands of requests miss at once and hit the DB. Fixes: one request rebuilds while others wait (lock / single flight), refresh early before expiry, add random jitter to TTLs.'},
  {tag:'Hot key',tc:'red',title:'One key gets huge traffic',body:'One cache node melts. Fixes: replicate the key to several nodes (key#1..key#5), or keep a tiny in-process copy for a few seconds.'},
  {tag:'Cold start',tc:'amber',title:'Cache restarts empty',body:'All traffic goes to the DB. Fixes: warm the most popular keys first, ramp traffic gradually, keep a replica so the DB can absorb it.'}]},
 {t:'reveal',title:'Interview questions',items:[
  {q:'Why delete the cache key on update instead of setting the new value?',a:'Two writers can race: A sets old value after B set the new one, leaving the cache wrong until TTL. Delete makes the next reader load the latest value from the DB.'},
  {q:'What eviction policy would you use and why?',a:'LRU for most workloads: recently used items are likely used again. LFU when popularity is stable over long periods. TTL for data that must expire.'},
  {q:'How big should the cache be?',a:'Size it to the hot set: e.g. 20% of items get 80% of reads. 1 M products × 2 KB × 20% ≈ 400 MB: one cache node.'}]},
 {t:'scalelab',id:'s04scale',title:'Scaling lab · The product page under load',level:'i',system:'<b>Initial system:</b> Client → API → PostgreSQL. 95% of requests are reads; a small set of products gets most of them. Raise the traffic, read the metrics, name the bottleneck, change one thing, measure again. Then press <b>Kill Redis</b>.',
  model:{readFrac:0.95,hitRate:0.9,cdnFrac:0.4},steps:[100,1000,5000,10000,50000],goal:10000,allow:['api','lb','cache','replicas','cdn','resilient'],fails:['cache','db','api','slowdb'],
  presets:[{l:'Simple',st:{ti:0,api:1},why:'One server and one database are right at 100 req/s.'},{l:'Scale to 10K req/s',st:{ti:3,api:7,lb:true,cache:true,replicas:1},why:'Stateless API servers behind a load balancer; Redis absorbs most reads; a replica adds read capacity and failover.'},{l:'Scale to 50K req/s',st:{ti:4,api:25,lb:true,cache:true,replicas:2,cdn:true},why:'The CDN serves cacheable pages for anonymous users; Redis serves most of the rest.'}]},
 {t:'predict',kind:'debug',title:'Debugging scenario · Fast on average, slow at the tail',level:'i',scenario:'A week after adding Redis, the dashboard shows:',metrics:[['p50','70 ms','ok'],['p95','180 ms','warn'],['p99','4.8 s','bad'],['API CPU','42%','ok'],['DB CPU','47%','ok'],['DB connections','normal','ok'],['Cache hit rate','97%','ok']],q:'What would you investigate next?',
  hints:['1 in 100 requests is very slow, but no resource is saturated. What do slow requests have in common?','What happens at the moment a popular key expires?'],
  opts:[['What the slowest 1% share: cache misses on hot keys (stampedes) and calls without timeouts',1,'Averages hide the tail. A hot key expiring sends a burst of misses to the database; requests without timeouts wait seconds. Check traces for the slowest requests.'],['Add API servers',0,'API CPU is 42%. Adding servers will not change a tail caused by a few slow paths.'],['Nothing: the average is fine',0,'A page that makes 20 backend calls hits the p99 on most page loads. Users feel the tail.'],['Shard the database',0,'DB CPU 47% and normal connections: the database is not saturated.']],
  takeaway:'Never conclude from averages. Look at the distribution, then at what the slow requests have in common: misses, one hot key, a slow dependency, GC pauses.'},
 {t:'hints',title:'Think it through · Overloaded by reads',level:'f',q:'"Our database is overloaded, mostly by reads." What would you do? Write your answer, then use the hints only if you need them.',write:true,hints:['Look at the read/write ratio, and at how skewed the reads are.','Can some reads be served somewhere other than the primary database?'],solution:'Consider a cache when a small hot set gets most reads and slight staleness is fine, and/or read replicas when reads are spread out or need real queries. Measure the hit rate and replica lag. Sharding is for write volume or data size, not repeated reads.'}]},

{title:'Guided problem and review',tab:'Guided + review',mins:20,out:'Cache plan for a product page',blocks:[
 {t:'stepper',title:'Guided · Speed up an e-commerce product page',steps:[
  {title:'Find the load',short:'Load',secs:90,think:'5 M product views a day, 2 M products, page takes 800 ms. Where does time go?',answer:'Page HTML + images + price + stock + reviews. Images and JS are the heaviest; product details rarely change; price and stock change more often.'},
  {title:'Place caches',short:'Place',secs:150,think:'Assign each piece of the page to a cache layer and TTL.',answer:'<ul class="clean"><li>Images, JS, CSS → CDN, TTL 1 year with versioned file names.</li><li>Product details, reviews summary → Redis, cache-aside, TTL 10 min, delete on edit.</li><li>Price → Redis, TTL 60 s.</li><li>Stock → read live at checkout; show "in stock" from cache on the page.</li></ul>'},
  {title:'Challenge',short:'Challenge',secs:120,think:'A flash sale makes one product 100x hotter, and its price changes at 12:00 sharp.',answer:'Hot key: keep that product in each app server\'s memory for 2 s. Price change: delete the key at 12:00 and use single-flight so only one request reloads it. Checkout always re-reads price from the DB.'}]},
 {t:'checkpoint',id:'s04cp',title:'Interview checkpoint',prompt:'"Our product page takes 800 ms, and the database hits 90% CPU during sales. How would you use caching to fix it?"',
  steps:['Ask for numbers: read/write ratio, skew, how stale each piece may be','Find where the 800 ms goes (database, images, other services)','Put each piece at the right layer: CDN, Redis, in-process, or no cache','Pick a pattern (cache-aside) and a TTL per piece','Say how writes invalidate (update DB, then delete the key)','Handle stampedes and hot keys','Name what must never come from cache (price and stock at checkout)','Say how you will measure success (hit rate, DB CPU, p99)'],
  model:'Images/JS → CDN with versioned names. Product details → Redis cache-aside, TTL 10 min, delete on edit. Price → TTL 60 s. Stock → cached for display, checked in the DB at checkout. Single-flight on misses and TTL jitter against stampedes; a short local cache for the flash-sale product. Success = hit rate > 90%, DB CPU < 50%, p99 < 300 ms.',
  followups:[['"The cache cluster restarts during the sale."','Cold cache: the database takes all reads. Warm the top products first, rate-limit rebuilds per key, keep replicas so the DB can absorb a spike.'],['"Two admins update the price at the same time."','Update the DB (last write wins or a version check), then delete the key. Deleting avoids leaving the loser\'s value in the cache.'],['"How big is the cache?"','Hot set ≈ 20% of products × 2 KB. 2 M products → ~800 MB: one node plus a replica.'],['"Why not cache the whole page?"','Personalised parts (cart, recommendations) differ per user. Cache fragments, or the anonymous page at the CDN.']]},
 {t:'flash',items:[['Cache-aside in one line?','Read cache → on miss read DB → put in cache.'],['Write-back risk?','Data loss if the cache fails before flushing to the DB.'],['Stampede fix?','Single-flight lock, early refresh, TTL jitter.'],['CDN pull vs push?','Pull fetches from origin on first miss; push uploads ahead of time.'],['When not to cache?','Write-heavy, uniform access, or must-be-latest data.']]},
 {t:'task',title:'Homework',items:['Write a cache plan for a news website on election night: what to cache where, with TTLs, and how you handle the hot headline.']},
 {t:'recall',title:'Active recall · Answer before revealing',items:[
  ['What problem does caching solve?','Repeated reads of the same data waste database capacity and time. A cache serves them from memory, cutting latency and database load.'],
  ['Explain cache-aside in one breath.','Read the cache; on a miss read the database, store the value with a TTL, return it. On write: update the database, then delete the key.'],
  ['Why delete the key on write instead of setting it?','Two writers can race and leave an old value in the cache. Deleting makes the next reader load the latest value.'],
  ['What is a cache stampede, and two fixes?','A hot key expires and many requests miss at once, all hitting the database. Fixes: single-flight (one rebuilds, others wait), early refresh, TTL jitter.'],
  ['When should you NOT cache?','Write-heavy or uniformly accessed data, and data that must always be current (balance at payment, stock at checkout).'],
  ['Why can more Redis nodes not fix one hot key?','A key lives on one node. Replicate the key (key#1..#n) or keep a short in-process copy.']]},
 {t:'summary',id:'s04sum',title:'Session summary',learned:['<b>Why caches exist:</b> repeated reads of a small hot set waste database capacity and time','<b>When to use one:</b> read-heavy, skewed, staleness-tolerant data','<b>When not to:</b> write-heavy, uniform, or must-be-current data','<b>Major trade-offs:</b> stale data, invalidation, stampedes, hot keys, cold starts','<b>Common interview questions:</b> which pattern, delete vs set, eviction policy, cache size'],explain:'Explain cache-aside, its four failure modes, and one fix for each, in 60 seconds.'}]}
],
labs:{
 lru(el,api){
  el.innerHTML=`<div class="form"><label>Cache size (items out of 1,000)<input type="range" min="10" max="500" step="10" value="100" data-c></label><label>Traffic skew<select data-s><option value="0">Uniform: every item equally popular</option><option value="0.8">Mild skew</option><option value="1.1" selected>Skewed (typical web)</option><option value="1.5">Very skewed (viral)</option></select></label><label>Eviction policy<select data-p><option value="lru">LRU: drop least recently used</option><option value="fifo">FIFO: drop oldest inserted</option></select></label></div><div class="out"><div><b data-cv></b><span>items cached</span></div><div><b data-h></b><span>hit rate</span></div><div><b data-db></b><span>DB reads/s at 2,000 req/s</span></div></div><div class="meter"><i data-m></i></div><div><p class="small muted">Last 60 requests (green = hit, red = miss)</p><div data-strip style="display:flex;flex-wrap:wrap;gap:2px;margin-top:6px"></div></div><div class="verdict" data-v></div>`;
  const run=()=>{const C=+api.$('[data-c]',el).value,s=+api.$('[data-s]',el).value,pol=api.$('[data-p]',el).value,N=1000,REQ=20000;
   const w=[];let tot=0;for(let i=1;i<=N;i++){const x=s?1/Math.pow(i,s):1;w.push(x);tot+=x}const cdf=[];let acc=0;for(const x of w){acc+=x/tot;cdf.push(acc)}
   let seed=42;const rnd=()=>{seed=(seed*1103515245+12345)%2147483648;return seed/2147483648};
   const pick=()=>{const r=rnd();let lo=0,hi=N-1;while(lo<hi){const m=(lo+hi)>>1;if(cdf[m]<r)lo=m+1;else hi=m}return lo};
   const cache=new Map();let hits=0;const strip=[];
   for(let i=0;i<REQ;i++){const k=pick();let hit=cache.has(k);if(hit){hits++;if(pol==='lru'){cache.delete(k);cache.set(k,1)}}else{cache.set(k,1);if(cache.size>C)cache.delete(cache.keys().next().value)}if(i>=REQ-60)strip.push(hit)}
   const hr=hits/REQ;api.$('[data-cv]',el).textContent=C+' ('+(C/10)+'%)';api.$('[data-h]',el).textContent=(hr*100).toFixed(1)+'%';api.$('[data-db]',el).textContent=Math.round(2000*(1-hr)).toLocaleString();api.$('[data-m]',el).style.width=(hr*100)+'%';
   api.$('[data-strip]',el).innerHTML=strip.map(h=>`<span style="width:12px;height:12px;border-radius:2px;background:${h?'var(--good)':'var(--marker)'}"></span>`).join('');
   api.$('[data-v]',el).innerHTML=s===0?'With uniform traffic the hit rate is roughly the cache size divided by the number of items. Caching barely helps.':`Caching ${C/10}% of items serves ${(hr*100).toFixed(0)}% of reads, because a few items get most of the traffic. The database now handles ${Math.round(2000*(1-hr)).toLocaleString()} reads/s instead of 2,000.`};
  el.addEventListener('input',run);el.addEventListener('change',run);run()}
}});
