COURSE.add({id:'s05',n:5,part:'A',track:'HLD',
title:'Scaling data: replication, sharding and consistent hashing',
goal:'Grow beyond one database: copy data for reads and safety, split data for size and writes, and move as little as possible when you add machines.',
outcomes:['Compare leader-follower, multi-leader and leaderless replication','Choose a shard key and spot hot partitions','Explain why consistent hashing moves fewer keys','Shard a real dataset in an interview'],
concept:'replication',
tasks:[{t:'Explain why read replicas help reads but not writes.'},{t:'Run the replication lab: lag, stale read, kill the primary, fail over.',auto:'s05repl'},{t:'Identify the bottleneck that justifies sharding.',auto:'s05bn'},{t:'Predict and count moved keys: % N vs consistent hashing.',auto:'s05shard'},{t:'Answer the sharding interview checkpoint.',auto:'s05cp'},{t:'Rate yourself: can you explain replication lag and failover without notes?',auto:'s05sum'}],
modules:[
{title:'Warm-up: recall session 4',tab:'Warm-up',mins:10,out:'Recall quiz',blocks:[
 {t:'mcq',items:[
  {q:'A hot key expires and the DB is flooded. This is a…',opts:['Cache stampede','Cache miss','Write-back'],a:0},
  {q:'On product update, the cache key should be…',opts:['Set to the new value','Deleted'],a:1},
  {q:'Uniform traffic, 10% cache. Hit rate is about…',opts:['10%','90%'],a:0}]}]},

{title:'Scale up or scale out; replication',tab:'Replication',mins:30,out:'Pick a replication model',lead:'Vertical scaling buys a bigger machine. Horizontal scaling adds machines. Replication copies the same data to several machines.',blocks:[
 {t:'grid',cols:2,title:'Vertical vs horizontal',items:[
  {tag:'Scale up',title:'Bigger machine',body:'No code changes; strong consistency stays easy. Has a ceiling, gets expensive, and is still one point of failure. Often the right first step.'},
  {tag:'Scale out',tc:'amber',title:'More machines',body:'Nearly unlimited; survives machine loss. Needs data to be copied or split, which brings consistency and routing problems.'}]},
 {t:'cards',title:'Three replication models',items:[
  {tag:'Most common',title:'Leader–follower',sub:'One writer, many readers',body:'<p>All writes go to the leader; followers copy its log and serve reads.</p><p><b>Good:</b> simple, no write conflicts. <b>Cost:</b> followers lag (stale reads); writes limited to one machine; failover needed if the leader dies.</p><p><b>Sync vs async:</b> synchronous followers never lose data but slow every write; async is fast but can lose the last few writes on failover.</p>'},
  {tag:'Multi-region',title:'Multi-leader',sub:'Writers in several places',body:'<p>Each region has a leader; leaders sync with each other.</p><p><b>Good:</b> local writes in every region. <b>Cost:</b> two regions can edit the same row: you need conflict rules (last-write-wins, merge, CRDTs).</p>'},
  {tag:'Dynamo-style',title:'Leaderless',sub:'Write to many, read from many',body:'<p>Clients write to W of N replicas and read from R. If R + W > N, a read overlaps the latest write.</p><p><b>Good:</b> no failover, high availability. <b>Cost:</b> conflict handling, repair processes. (Session 6 has a lab.)</p>'}]},
 {t:'reveal',items:[
  {q:'A user updates their profile, refreshes, and sees the old name. Why, and how do you fix it?',a:'They read from a lagging follower. Fix: <b>read-your-own-writes</b>: route a user\'s reads to the leader for a short time after they write, or read from a follower only if it has caught up to the user\'s last write position.'},
  {q:'The leader dies. What happens with async replication?',a:'A follower is promoted. Writes not yet copied are lost or must be reconciled. That is why payment systems often use synchronous replication to at least one follower.'}]},
 {t:'diagram',title:'Diagram · Primary / replica architecture',level:'f',nodes:['api@0,1:API servers','db@1,1:Primary|all writes','replica1@2,0:Replica 1|reads','replica2@2,2:Replica 2|reads'],edges:['api>db:writes','db~>replica1:replication log','db~>replica2:replication log','api>replica1:reads'],caption:'The primary writes changes to a log; replicas replay it. Reads spread across replicas; writes still go to one primary. Async replication means replicas are milliseconds to seconds behind.'},
 {t:'replsim',id:'s05repl',title:'Lab · Replication, lag and failover',level:'i',concept:'replication',intro:'Write values, introduce lag, read from a replica, then kill the primary. Answer the questions before you fail over.'},
 {t:'diagram',title:'Diagram · Failover and leader election',concept:'replication',nodes:['mon@1,0:Health monitor|or consensus (Raft)','db@0,1:Old primary','replica1@1,1:Replica 1|most up to date','replica2@2,1:Replica 2','api@1,2:API servers'],edges:['mon>db:heartbeat','mon>replica1','mon>replica2','api>replica1:writes after failover'],
  steps:[{hi:['mon','db'],txt:'The monitor sends heartbeats to the primary.',states:{}},{hi:['mon','db'],states:{db:'down'},txt:'Heartbeats fail for a few seconds. Is it dead, or just slow? Waiting too little causes false failovers; too long means downtime.'},{hi:['mon','replica1','replica2'],states:{db:'down'},txt:'The monitor (or a consensus vote among nodes) picks the most up-to-date replica.'},{hi:['replica1'],states:{db:'down',replica1:'new'},txt:'Replica 1 is promoted. Writes it never received from the old primary are lost under async replication.'},{hi:['api','replica1'],states:{db:'down',replica1:'new'},txt:'Clients are redirected (DNS, proxy or service discovery). If the old primary comes back, it must be fenced so two primaries never accept writes (split brain).'}]}]},

{title:'Sharding (partitioning)',tab:'Sharding',mins:30,out:'Choose a shard key',lead:'Sharding splits data so each machine holds a part. You do it when data or writes outgrow one machine. The shard key decides everything.',blocks:[
 {t:'table',title:'Ways to split',head:['Strategy','How','Good','Risk'],rows:[
  ['Range','Users A–F on shard 1, G–M on shard 2…; or by date','Range queries are easy','Hot shards (new dates all on one shard)'],
  ['Hash','shard = hash(key) mod N','Even spread','Range queries hit every shard; changing N moves most keys'],
  ['Consistent hash','Keys and servers placed on a ring','Adding a server moves few keys','More complex; needs virtual nodes for balance'],
  ['Directory / lookup','A table says which shard holds which key','Full control, easy moves','The directory is a dependency to keep fast and available']]},
 {t:'mcq',title:'Pick the shard key',items:[
  {q:'Chat messages, always read by conversation.',opts:['message_id','conversation_id','sent_at date'],a:1,why:'All messages of a conversation live together; one shard answers the read.'},
  {q:'An orders table where most queries are "orders of user X".',opts:['user_id','order_date','country'],a:0,why:'Matches the main query. Date would put all of today\'s writes on one hot shard.'},
  {q:'Metrics time series, queried by sensor and time range.',opts:['timestamp only','sensor_id (+ time inside the shard)','random'],a:1,why:'Timestamp alone makes one shard take all current writes.'},
  {q:'A celebrity\'s posts get 1,000x more reads than others, sharded by user_id. Fix?',opts:['Reshard by date','Cache / replicate that user\'s data','Bigger single DB'],a:1,why:'Hot keys are solved with caching or replication, not by changing the key.'}]},
 {t:'grid',title:'Costs of sharding to say out loud',items:[
  {title:'Cross-shard queries',body:'"Top 10 products overall" must ask every shard and merge.'},
  {title:'Cross-shard transactions',body:'A transfer between users on two shards needs 2PC or a saga (session 6).'},
  {title:'Resharding',body:'Moving data while serving traffic is hard; plan with consistent hashing or many small logical shards.'},
  {title:'Unique IDs',body:'Auto-increment per shard collides; use globally unique IDs (Snowflake-style or UUIDs).'}]},
 {t:'predict',id:'s05bn',kind:'bottleneck',concept:'sharding',title:'Where is the bottleneck?',level:'i',scenario:'A messaging service after adding a cache and two replicas:',metrics:[['API CPU','20%','ok'],['Redis CPU','15%','ok'],['Primary DB CPU','96%','bad'],['Primary DB connections','98%','bad'],['Replica CPU','12%','ok'],['Writes / s','40,000','bad'],['Data size','6 TB','warn'],['Queue depth','0','ok']],q:'What would you change?',
  hints:['Look at which machines are idle and which one is not.','Do replicas and caches reduce writes?'],
  opts:[['Shard the database by conversation_id',1,'Writes and size overwhelm one primary. Replicas copy every write, and caches only absorb reads. Splitting by key gives each shard a share of the writes.'],['Add more read replicas',0,'Replicas are at 12%: reads are not the problem, and each replica must apply every write too.'],['Add more API servers',0,'API CPU is 20%.'],['A bigger Redis cluster',0,'Redis is at 15% and does not absorb writes.']],
  takeaway:'Sharding is justified by write volume or data size that exceeds one machine, after caches and replicas have handled the reads.'},
 {t:'diagram',title:'Diagram · Sharding with a router',concept:'sharding',nodes:['api@0,1:API servers','proxy@1,1:Shard router|hash(user_id)','shard1@2,0:Shard A|users 0–⅓','shard2@2,1:Shard B|users ⅓–⅔','shard3@2,2:Shard C|users ⅔–1'],edges:['api>proxy','proxy>shard1','proxy>shard2','proxy>shard3'],caption:'Every query must carry the shard key. A query without it (e.g. "all users named Asha") must ask every shard: scatter-gather.'},
 {t:'shardsim',id:'s05shard',title:'Lab · Moving keys: hash % N vs consistent hashing',level:'i',concept:'sharding',intro:'Twenty users on three shards. Predict, add a fourth shard, and count how many users move.'},
 {t:'hints',title:'Think it through · When is sharding premature?',concept:'sharding',q:'Your database is at 70% CPU at peak, mostly reads, with 300 GB of data. A teammate proposes sharding. What do you say?',write:true,hints:['What do the numbers say: reads or writes? Size?','What simpler changes would buy time, and what new problems would sharding bring?'],solution:'Premature. Reads dominate and 300 GB fits one machine: add a cache and read replicas, tune queries and indexes, scale the machine up. Sharding brings routing, cross-shard queries and joins, rebalancing and hot shards. Revisit when writes or size, not reads, exceed one primary.'}]},

{title:'Lab: consistent hashing',tab:'Lab',mins:25,out:'Explain why few keys move',lead:'Add a server and compare how many of 10,000 keys must move with <code>hash mod N</code> versus a hash ring.',blocks:[
 {t:'lab',fn:'ring'},
 {t:'teacher',items:['Start with 4 servers and 1 virtual node each. Add a server: mod N moves ~80% of keys, the ring ~20% but load is uneven. Raise virtual nodes to 100: moves stay ~1/N and load evens out.','Interview phrasing: "With consistent hashing, adding the Nth server moves about 1/N of the keys."']}]},

{title:'Guided problem: shard a URL store',tab:'Guided problem',mins:25,out:'A sharding plan with numbers',blocks:[
 {t:'stepper',steps:[
  {title:'Do we need to shard?',short:'Need?',secs:120,think:'1.8 billion links, ~1 TB, 12 writes/s, 3,500 reads/s at peak. One database?',answer:'Writes are tiny. Reads are handled by a cache + replicas. Storage of 1 TB fits on one large machine today. <b>Answer:</b> not on day one; plan for it when data passes a few TB or for multi-region. Saying this scores well.'},
  {title:'Choose the key',short:'Key',secs:120,think:'If we shard later, what key?',answer:'shortCode: every lookup carries it, and hashing it spreads load evenly. No range queries are needed.'},
  {title:'Plan for growth',short:'Growth',secs:150,think:'How do we add shards later without moving everything?',answer:'Start with 256 logical shards mapped onto 4 machines. Growing = moving whole logical shards to new machines (copy, catch up, switch the mapping). Or use consistent hashing with virtual nodes.'},
  {title:'Challenge',short:'Challenge',secs:120,think:'Analytics wants "all links created by user X". Shard key is shortCode. What now?',answer:'That query would hit every shard. Keep a secondary table partitioned by userId (userId → list of codes), written alongside, or send events to an analytics store. Cost: two writes per create, possible brief mismatch.'}]},
 {t:'flash',title:'Review',items:[['Leader–follower downside?','Replication lag (stale reads) and one write leader.'],['Read-your-own-writes?','After a write, read that user\'s data from the leader or a caught-up replica.'],['Hash mod N problem?','Changing N remaps almost every key.'],['Virtual nodes?','Many ring positions per server to even out load.'],['Hot shard fix?','Cache or replicate hot keys; better key choice; split the hot range.'],['IDs across shards?','Globally unique IDs, e.g. timestamp + machine + sequence.']]},
 {t:'task',title:'Homework',items:['Pick shard keys for: Twitter tweets, Uber trips, a stock-trading order book. One line of reasoning each.']},
 {t:'checkpoint',id:'s05cp',concept:'sharding',title:'Interview checkpoint',prompt:'"Our user database has 2 billion rows and 50 K writes per second. How would you shard it?"',steps:['Confirm that writes/size, not reads, are the bottleneck','Choose a shard key from the hot access pattern (user_id)','Choose the function: hash, range or directory','Plan for adding shards (consistent hashing / many virtual shards)','Handle queries without the key (secondary index, scatter-gather)','Handle hot keys / celebrity users','Keep replicas per shard for failover','Plan the migration (dual writes, backfill, cut-over)'],
  model:'Shard by hash(user_id) into many logical shards (e.g. 1,024) mapped to fewer physical nodes; move logical shards when adding nodes. A lookup table or global secondary index for email → user_id. Each shard has replicas with automatic failover. Celebrities: split their heavy data further or cache it.',followups:[['"How do you find a user by email?"','A separate email → user_id index (itself sharded by email), or scatter-gather if rare.'],['"One shard is twice as busy."','Hot key or uneven ranges. Split that logical shard, or move it to its own node.']]},
 {t:'recall',title:'Active recall',items:[['Why do we use read replicas?','To add read capacity and a standby that can be promoted if the primary fails.'],['What is replication lag?','The delay before a replica applies a write from the primary. Reads from a lagging replica can be stale.'],['When would sharding be premature?','When reads, not writes or data size, are the problem, or when caching, replicas and indexes have not been tried.','sharding'],['Why does hash % N reshuffle almost every key?','Changing N changes nearly every key’s remainder. Consistent hashing moves only ~1/N of keys.','sharding'],['What is split brain?','Two nodes both believe they are primary and accept writes. Prevent it with fencing and quorums.']]},
 {t:'summary',id:'s05sum',title:'Session summary',learned:['<b>Why replicas exist:</b> read capacity and failover','<b>Why shards exist:</b> write volume and data size beyond one machine','<b>When not to shard:</b> when caches, replicas or indexes solve the bottleneck','<b>Trade-offs:</b> lag and stale reads; routing, rebalancing, hot shards, cross-shard queries','<b>Interview questions:</b> shard key choice, adding shards, failover, split brain'],explain:'Explain replication lag, failover data loss, and how consistent hashing limits key movement.'}]}
],
labs:{
 ring(el,api){
  const H=s=>{let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)>>>0}h^=h>>>13;h=Math.imul(h,0x5bd1e995)>>>0;h^=h>>>15;return h>>>0};
  const cols=['var(--accent)','var(--good)','var(--warn)','var(--marker)','var(--lld)','var(--muted)','var(--ink)'];
  el.innerHTML=`<div class="form"><label>Servers now: <b data-nv></b><input type="range" min="2" max="6" value="4" data-n></label><label>Virtual nodes per server: <b data-vv></b><input type="range" min="1" max="200" value="1" data-v></label></div><div class="grid2" style="align-items:center"><div class="svgbox" style="max-width:340px"><svg viewBox="0 0 300 300" data-svg role="img" aria-label="Hash ring"></svg></div><div class="col"><div class="out"><div><b data-mod></b><span>keys moved, hash mod N → N+1</span></div><div><b data-rg></b><span>keys moved on the ring</span></div><div><b data-ideal></b><span>ideal (1/(N+1))</span></div><div><b data-bal></b><span>busiest server vs average (ring)</span></div></div></div></div><div class="verdict" data-out></div>`;
  const K=10000;const keys=[];for(let i=0;i<K;i++)keys.push(H('key-'+i));
  const ring=(n,v)=>{const pts=[];for(let s=0;s<n;s++)for(let j=0;j<v;j++)pts.push([H('server-'+s+'#'+j),s]);pts.sort((a,b)=>a[0]-b[0]);return pts};
  const owner=(pts,h)=>{let lo=0,hi=pts.length;while(lo<hi){const m=(lo+hi)>>1;if(pts[m][0]<h)lo=m+1;else hi=m}return pts[lo===pts.length?0:lo][1]};
  const draw=()=>{const n=+api.$('[data-n]',el).value,v=+api.$('[data-v]',el).value;api.$('[data-nv]',el).textContent=n+' → adding 1';api.$('[data-vv]',el).textContent=v;
   const A=ring(n,v),B=ring(n+1,v);let mm=0,rm=0;const load=new Array(n+1).fill(0);
   for(const h of keys){if(h%n!==h%(n+1))mm++;const a=owner(A,h),b=owner(B,h);if(a!==b)rm++;load[b]++}
   const avg=K/(n+1),mx=Math.max(...load);
   api.$('[data-mod]',el).textContent=(mm/K*100).toFixed(0)+'%';api.$('[data-rg]',el).textContent=(rm/K*100).toFixed(0)+'%';api.$('[data-ideal]',el).textContent=(100/(n+1)).toFixed(0)+'%';api.$('[data-bal]',el).textContent=(mx/avg).toFixed(2)+'x';
   const pts=B.length>300?B.filter((_,i)=>i%Math.ceil(B.length/300)===0):B;
   api.$('[data-svg]',el).innerHTML=`<circle cx="150" cy="150" r="110" fill="none" stroke="var(--line)" stroke-width="10"/>`+pts.map(p=>{const a=p[0]/4294967296*Math.PI*2-Math.PI/2;return `<circle cx="${(150+110*Math.cos(a)).toFixed(1)}" cy="${(150+110*Math.sin(a)).toFixed(1)}" r="${v>20?3:6}" fill="${cols[p[1]%cols.length]}"/>`}).join('')+`<text x="150" y="146" text-anchor="middle" font-size="13" fill="var(--ink)" font-weight="600">${n+1} servers</text><text x="150" y="164" text-anchor="middle" font-size="11" fill="var(--muted)">${v} point${v>1?'s':''} each</text>`;
   api.$('[data-out]',el).innerHTML=`With <code>hash mod N</code>, going from ${n} to ${n+1} servers moves <b>${(mm/K*100).toFixed(0)}%</b> of keys: almost a full reshuffle and a cache wipe. On the ring only <b>${(rm/K*100).toFixed(0)}%</b> move. ${v<20?'With few virtual nodes the busiest server holds '+(mx/avg).toFixed(1)+'x the average: raise virtual nodes to balance it.':'Many virtual nodes keep load close to even.'}`};
  el.addEventListener('input',draw);draw()}
}});
