COURSE.add({id:'s07',n:7,part:'A',track:'HLD',
title:'Async processing: queues, streams and events',
goal:'Move slow or spiky work out of the request path, and make it reliable when messages are lost, delayed or duplicated.',
outcomes:['Decide what should be synchronous and what asynchronous','Compare a job queue, pub/sub and a log (Kafka-style)','Use retries, backoff, dead-letter queues and idempotent consumers','Design a notification system'],
concept:'queues',
tasks:[{t:'Redesign the 8-second upload request (answer the prediction).',auto:'s07pred'},{t:'Run the queue lab: grow the backlog, then add workers until it is stable.',auto:'s07q'},{t:'Explain pub/sub vs a work queue using the diagrams.'},{t:'Explain retries, dead-letter queues and idempotent consumers.'},{t:'Answer the notification-system interview checkpoint.',auto:'s07cp'},{t:'Rate yourself: can you explain backpressure without notes?',auto:'s07sum'}],
modules:[
{title:'Warm-up: recall session 6',tab:'Warm-up',mins:10,out:'Recall quiz',blocks:[
 {t:'mcq',items:[
  {q:'N=3, W=2, R=2. Reads see the latest write?',opts:['Yes','No'],a:0},
  {q:'Order → payment → shipping across services. Coordinate with…',opts:['A saga','A bigger database'],a:0},
  {q:'"Exactly once" in practice means…',opts:['The network never duplicates','At-least-once + idempotent processing'],a:1}]}]},

{title:'Sync vs async; queue, pub/sub, log',tab:'Messaging',mins:25,out:'Choose a messaging type',lead:'If the user does not need the result to continue, do the work later. A message broker sits between the producer and the workers.',blocks:[
 {t:'grid',cols:2,title:'What async buys you',items:[
  {tag:'Faster responses',title:'Return before the slow part',body:'Sign-up returns in 80 ms; the welcome email, thumbnail and analytics happen afterwards.'},
  {tag:'Absorb spikes',title:'The queue is a buffer',body:'10,000 orders in a minute queue up; workers drain them at their own pace instead of crashing.'},
  {tag:'Decoupling',title:'Producers do not know consumers',body:'Add a new consumer (fraud check) without changing the order service.'},
  {tag:'Cost',tc:'red',title:'What you pay',body:'Delay, harder debugging, duplicate and out-of-order messages, and one more system to run.'}]},
 {t:'table',title:'Three messaging shapes',head:['Shape','Delivery','After reading','Example'],rows:[
  ['Job / work queue','Each message to one worker','Deleted','Resize this image; send this email (SQS, RabbitMQ)'],
  ['Pub/sub','Each message to every subscriber','Gone after delivery','"Order placed" → email, analytics, inventory each get a copy'],
  ['Log / stream','Consumers read at their own offset','Kept for days; can replay','Kafka: clickstream, change events, rebuilding a search index']]},
 {t:'mcq',title:'Which shape?',items:[
  {q:'Transcode each uploaded video exactly by one of 50 workers.',opts:['Job queue','Pub/sub','Nothing: do it in the request'],a:0},
  {q:'"Payment succeeded" must reach the email, ledger and analytics services.',opts:['Job queue','Pub/sub or a log topic'],a:1},
  {q:'A new team wants to reprocess the last 7 days of click events.',opts:['Job queue','Log with retention (Kafka-style)'],a:1},
  {q:'Show the price after the user clicks "Buy".',opts:['Async','Sync: the user needs it now'],a:1}]},
 {t:'predict',id:'s07pred',title:'What happens next?',level:'f',scenario:'Upload flow today: <b>Client → API → Image processing → Database</b>. Each request takes <b>8 seconds</b> and holds an API thread the whole time. During a promotion, uploads triple and requests start timing out.',metrics:[['Request time','8 s','bad'],['API thread pool','100%','bad'],['API CPU','35%','ok'],['DB CPU','20%','ok']],q:'How would you redesign it?',
  opts:[['API stores the upload, enqueues a job, replies 202; workers process',1,'The user gets an answer in ~50 ms; slow work runs in the background at its own pace, and spikes wait in the queue.'],['Add more API servers',0,'Each request still holds a thread for 8 s; you would need 3× the servers just to wait.'],['Increase the timeout to 30 s',0,'Users wait longer and threads stay blocked.'],['Cache the processed images',0,'New uploads are never in the cache.']],takeaway:'Move slow, non-interactive work out of the request path. The cost: results arrive later, and you must handle retries and failures in the background.'},
 {t:'diagram',title:'Diagram · Work queue vs pub/sub',nodes:['api@0,0:Order API','queue@1,0:Work queue','worker1@2,0:Worker pool|each job once','api2@0,2:Order API','topic@1,2:Topic: order.placed','sub1@2,1:Email service','sub2@2,2:Analytics','sub3@2,3:Inventory'],edges:['api>queue','queue>worker1:one consumer per job','api2>topic','topic>sub1','topic>sub2','topic>sub3'],caption:'A work queue gives each job to one worker (spread the work). Pub/sub gives each event to every subscriber (fan out a fact). A log (Kafka) keeps events so new consumers can replay them.'},
 {t:'diagram',title:'Diagram · Event-driven order flow',nodes:['client@0,1:Client','api@1,1:Order service','kafka@2,1:Event log','pay@3,0:Payment service','inv@3,1:Inventory service','mail@3,2:Notification service'],edges:['client>api:place order','api>kafka:OrderPlaced','kafka>pay','kafka>inv','kafka>mail'],
  steps:[{hi:['client','api'],txt:'The order service saves the order (status: pending) and replies at once.'},{hi:['api','kafka'],txt:'It publishes <code>OrderPlaced</code>. It does not know who listens: loose coupling.'},{hi:['kafka','pay','inv','mail'],txt:'Each service reacts independently, at its own speed. One being slow does not block the others.'},{hi:['kafka','pay'],states:{pay:'warn'},txt:'Cost: the flow is harder to trace, and failures need compensation (a saga): if payment fails, release the reserved stock.'}]}]},

{title:'Reliable delivery',tab:'Reliability',mins:20,out:'Retry policy for a consumer',blocks:[
 {t:'cards',items:[
  {tag:'At-most-once',title:'Fire and forget',body:'<p>Acknowledge before processing. Fast, but a crash loses the message. OK for metrics sampling.</p>'},
  {tag:'At-least-once',title:'Default choice',body:'<p>Acknowledge after processing. A crash causes a redelivery, so <b>consumers must be idempotent</b> (store processed message IDs, or use upserts).</p>'},
  {tag:'Retries + backoff',title:'Wait longer each time',body:'<p>Retry after 1 s, 2 s, 4 s, 8 s… with random jitter so thousands of clients do not retry in lockstep. Cap the attempts.</p>'},
  {tag:'Dead-letter queue',title:'Park poison messages',body:'<p>After N failures, move the message to a DLQ for inspection, so one bad message does not block the queue forever.</p>'},
  {tag:'Ordering',title:'Only where needed',body:'<p>Global order is slow. Order per key instead: Kafka keeps order within a partition, so partition by orderId.</p>'}]},
 {t:'code',title:'An idempotent consumer',code:`
def handle(message):
    if processed.exists(message.id):          # seen before: a redelivery
        return ack(message)
    with db.transaction():
        apply_business_change(message.body)  # e.g. add points to a wallet
        processed.insert(message.id)          # same transaction as the change
    ack(message)`,note:'Storing the message ID in the same transaction as the change is what makes it safe.'},
 {t:'grid',title:'Two patterns to name in interviews',items:[
  {title:'Transactional outbox',body:'The service writes the order <b>and</b> an "order placed" row in its own DB in one transaction; a relay publishes outbox rows to the broker. No more "saved but event lost".'},
  {title:'CQRS / event sourcing (light)',body:'Write side stores events; read side builds views (search index, dashboards) from them. Powerful for audit and replay; costs complexity and eventual consistency.'}]},
 {t:'diagram',title:'Diagram · Retries, backoff and the dead-letter queue',nodes:['queue@0,1:Queue','worker@1,1:Worker|idempotent handler','provider@2,1:Email provider','dlq@1,2:Dead-letter queue','mon@2,2:Alert + manual review'],edges:['queue>worker','worker>provider','worker~>queue:retry with backoff','worker>dlq:after 5 attempts','dlq>mon'],
  steps:[{hi:['queue','worker','provider'],txt:'The worker takes a message and calls the provider.'},{hi:['worker','provider'],states:{provider:'down'},txt:'The provider fails. The message is not acknowledged, so it returns to the queue.'},{hi:['worker','queue'],txt:'Retry after 1 s, 2 s, 4 s, 8 s (exponential backoff + jitter) so a struggling provider is not hammered.'},{hi:['worker','dlq'],states:{dlq:'warn'},txt:'After 5 attempts the message moves to the <b>dead-letter queue</b>. A poison message no longer blocks everything behind it.'},{hi:['dlq','mon'],txt:'Alert on DLQ size; fix and replay. Because delivery is at-least-once, the handler must be idempotent.'}]}]},

{title:'Lab: will the queue keep up?',tab:'Lab',mins:25,out:'Size workers for a load',lead:'A queue only helps if workers drain it faster than it fills on average. Simulate two minutes of traffic.',blocks:[
 {t:'queuesim',id:'s07q',title:'Lab · Synchronous vs queue + workers, with backpressure',level:'i',intro:'Run the synchronous version first. Then switch to async: start with too few workers, watch the backlog grow, add workers until throughput matches arrivals. Try the burst and "Stop all workers".'},
 {t:'lab',fn:'queue'},
 {t:'teacher',items:['Show Little\'s law informally: workers needed ≈ arrival rate × processing time. 200 msg/s × 0.05 s = 10 workers at full use; add headroom.','Turn on the burst: a backlog forms then drains. Ask: "Is a 40-second delay OK for emails? For OTP codes?"']}]},

{title:'Guided problem: a notification system',tab:'Guided problem',mins:30,out:'Notification design + failure answers',lead:'Prompt: <b>"Design a service that sends email, SMS and push notifications for other teams."</b>',blocks:[
 {t:'stepper',steps:[
  {title:'Clarify',short:'Clarify',secs:150,think:'Volumes? Priorities? User preferences?',answer:'<ul class="clean"><li>50 M notifications/day, bursts 10x during campaigns.</li><li>Channels: email, SMS, push. Priorities: OTP/security (seconds) vs marketing (minutes–hours).</li><li>Respect user opt-outs and quiet hours; no duplicates; track delivered/failed.</li></ul>'},
  {title:'API and data',short:'API',secs:150,think:'What does a calling team send?',answer:'<p><code>POST /v1/notifications {userId, template, params, channels?, priority, idempotencyKey}</code> → 202 Accepted + id.</p><p>Data: <b>Preference</b>(userId, channel, optedIn, quietHours), <b>Template</b>, <b>Notification</b>(id, userId, channel, status, attempts).</p>'},
  {title:'Design and break it',short:'Design',secs:300,think:'Draw it, then use the lab.',blocks:[{t:'arch',title:'Notification system lab',w:760,h:340,
   nodes:[{id:'api',x:20,y:130,w:120,label:'Notify API',sub:'validate, dedupe'},{id:'pref',x:20,y:240,w:120,label:'Preferences',sub:'opt-outs'},{id:'q',x:190,y:130,w:120,label:'Queues',sub:'per channel + priority',opt:'q'},{id:'we',x:370,y:40,w:130,label:'Email workers'},{id:'ws',x:370,y:130,w:130,label:'SMS workers'},{id:'wp',x:370,y:220,w:130,label:'Push workers'},{id:'pe',x:560,y:40,w:170,label:'Email provider',sub:'external'},{id:'ps',x:560,y:130,w:170,label:'SMS provider',sub:'external'},{id:'pp',x:560,y:220,w:170,label:'APNs / FCM',sub:'external'},{id:'dlq',x:370,y:292,w:130,h:40,label:'Dead letters',opt:'dlq'}],
   edges:[{d:'M140 158H190'},{d:'M80 186V240',dash:true,arrow:false,label:'check',lx:86,ly:218},{d:'M310 150H340V68H370',opt:'q'},{d:'M310 158H370',opt:'q'},{d:'M310 166H340V248H370',opt:'q'},{d:'M500 68H560'},{d:'M500 158H560'},{d:'M500 248H560'},{d:'M435 276V292',opt:'dlq'},{d:'M140 145H165V68H370',opt:'!q',label:'direct calls',lx:175,ly:60}],
   toggles:[{id:'q',label:'Queues between API and workers'},{id:'dlq',label:'Retries + dead-letter queue'}],
   fails:[
    {label:'Campaign burst: 10x traffic',run:o=>o.q?{lvl:'ok',oks:['q'],txt:'The queues absorb the burst. Marketing waits a few minutes; OTPs stay fast because they have their own high-priority queue.'}:{lvl:'bad',hits:['api','we'],txt:'Without queues, the API calls workers directly and times out under 10x load. Calling teams see errors and retry, making it worse.'}},
    {label:'SMS provider is down for 10 minutes',run:o=>o.q&&o.dlq?{lvl:'warn',hits:['ps'],oks:['dlq'],txt:'SMS workers retry with backoff; messages wait in the queue. After the limit they go to the dead-letter queue to replay later. Option: fail over to a second SMS provider for OTPs.'}:o.q?{lvl:'warn',hits:['ps','ws'],txt:'Messages pile up and workers keep retrying fast, hammering the provider. Add backoff and a dead-letter queue.'}:{lvl:'bad',hits:['ps','api'],txt:'Every request that includes SMS fails immediately; messages are lost.'}},
    {label:'A worker crashes after sending, before ack',run:o=>({lvl:'warn',hits:['we'],txt:'The message is redelivered and the user may get the email twice. Fix: store the notification id as "sent" before acking and check it first (idempotent consumer); providers often accept an idempotency key too.'})},
    {label:'User opted out of marketing',run:o=>({lvl:'ok',oks:['pref'],txt:'The API checks preferences before queueing (and workers re-check before sending, in case the user opted out while it was queued).'})}],
   start:'Start without queues (direct calls), then add queues and the dead-letter queue, and break things.'}]},
  {title:'Challenge',short:'Challenge',secs:180,think:'How do you stop one noisy team flooding everyone\'s notifications?',answer:'Per-caller rate limits at the API, separate queues per priority, and per-user limits ("max 3 marketing pushes a day"). Cost: some campaign messages are delayed or dropped by policy.'}]}]},

{title:'Review',tab:'Review',mins:10,out:'Flashcards + homework',blocks:[
 {t:'flash',items:[['Queue vs pub/sub?','Queue: one worker per message. Pub/sub: every subscriber gets a copy.'],['Why a log (Kafka)?','Retention and replay; ordered per partition; many independent consumers.'],['Dead-letter queue?','Where messages go after N failed attempts.'],['Outbox pattern?','Write the change and the event in one DB transaction; publish from the outbox.'],['Backoff with jitter?','Growing waits plus randomness so retries do not stampede.'],['Workers needed?','≈ arrival rate × processing time, plus headroom.']]},
 {t:'task',title:'Homework',items:['Design the async parts of a video upload pipeline: upload → transcode (4 resolutions) → thumbnail → notify followers.']},
 {t:'checkpoint',id:'s07cp',title:'Interview checkpoint',prompt:'"Design a notification service that sends email, SMS and push for 50 M users, including a 10 M-user marketing blast."',steps:['Clarify channels, volume, latency targets (OTP vs marketing)','Separate the API from delivery with a queue','Use separate queues/priorities per channel and urgency','Scale workers by queue depth; respect provider rate limits','Retries with backoff, idempotency keys, dead-letter queue','User preferences and opt-outs checked before sending','Track delivery status asynchronously (callbacks)','Explain the blast: batch fan-out, throttle, backpressure'],
  model:'API validates and enqueues; a fan-out worker expands campaigns into per-user jobs; per-channel queues with priority (OTP > transactional > marketing); channel workers call providers within their rate limits; retries + DLQ; status from provider webhooks stored per notification. The blast is throttled so OTPs never wait behind it.',followups:[['"Provider X is down for an hour."','Circuit breaker on X, fail over to provider Y; queue absorbs the backlog.'],['"A user got the same SMS twice."','At-least-once delivery: dedupe with an idempotency key per notification before calling the provider.']]},
 {t:'recall',title:'Active recall',items:[['Why put a queue in front of slow work?','The request returns at once; work runs at the workers’ pace; spikes wait in the queue instead of failing.'],['What is backpressure?','Pushing back on producers when consumers cannot keep up: bounded queues, 429s, slowing intake.'],['Work queue vs pub/sub?','Work queue: each message to one consumer. Pub/sub: each message to every subscriber.'],['Why must consumers be idempotent?','Queues deliver at least once; a message can be processed twice.'],['What is a dead-letter queue for?','Messages that keep failing go aside after N attempts, so they do not block the queue and can be inspected.']]},
 {t:'summary',id:'s07sum',title:'Session summary',learned:['<b>Why queues exist:</b> decouple slow or spiky work from the request path','<b>When to use one:</b> work the user does not need to wait for','<b>When not to:</b> reads that need an answer now','<b>Trade-offs:</b> eventual results, duplicates, ordering, monitoring queue age','<b>Interview questions:</b> delivery guarantees, DLQ, backpressure, pub/sub vs queue'],explain:'Explain why the queue grew, how many workers you needed, and what backpressure does.'}]}
],
labs:{
 queue(el,api){
  el.innerHTML=`<div class="form"><label>Messages arriving per second: <b data-av></b><input type="range" min="10" max="500" step="10" value="200" data-a></label><label>Workers: <b data-wv></b><input type="range" min="1" max="40" value="8" data-w></label><label>Time per message (ms): <b data-tv></b><input type="range" min="10" max="200" step="5" value="50" data-t></label><label class="check" style="flex-direction:row;align-items:center"><input type="checkbox" data-b checked> 20-second burst at 5x traffic</label></div><div class="svgbox"><svg viewBox="0 0 640 200" data-svg role="img" aria-label="Queue backlog over time"></svg></div><div class="out"><div><b data-cap></b><span>worker capacity (msg/s)</span></div><div><b data-max></b><span>largest backlog</span></div><div><b data-wait></b><span>worst wait in queue</span></div><div><b data-end></b><span>backlog after 2 minutes</span></div></div><div class="verdict" data-v></div>`;
  const draw=()=>{const a=+api.$('[data-a]',el).value,w=+api.$('[data-w]',el).value,t=+api.$('[data-t]',el).value,burst=api.$('[data-b]',el).checked;
   api.$('[data-av]',el).textContent=a;api.$('[data-wv]',el).textContent=w;api.$('[data-tv]',el).textContent=t;
   const cap=w*1000/t;let q=0;const pts=[];let mx=0;for(let s=0;s<120;s++){const inR=burst&&s>=30&&s<50?a*5:a;q=Math.max(0,q+inR-cap);pts.push(q);if(q>mx)mx=q}
   const top=Math.max(mx,10),X=i=>40+i*(580/119),Y=v=>180-v/top*160;
   api.$('[data-svg]',el).innerHTML=`<line x1="40" y1="180" x2="620" y2="180" stroke="var(--line)"/><line x1="40" y1="20" x2="40" y2="180" stroke="var(--line)"/>${burst?`<rect x="${X(30)}" y="20" width="${X(50)-X(30)}" height="160" fill="var(--warn-soft)"/><text x="${X(40)}" y="34" text-anchor="middle" font-size="11" fill="var(--warn)">burst</text>`:''}<path d="M${pts.map((v,i)=>X(i).toFixed(1)+' '+Y(v).toFixed(1)).join('L')}" fill="none" stroke="var(--accent)" stroke-width="2"/><text x="44" y="16" font-size="11" fill="var(--muted)">backlog: ${Math.round(top).toLocaleString()} msgs</text><text x="620" y="196" text-anchor="end" font-size="11" fill="var(--muted)">120 s</text><text x="40" y="196" font-size="11" fill="var(--muted)">0 s</text>`;
   api.$('[data-cap]',el).textContent=Math.round(cap).toLocaleString();api.$('[data-max]',el).textContent=Math.round(mx).toLocaleString();api.$('[data-wait]',el).textContent=(mx/cap).toFixed(1)+' s';api.$('[data-end]',el).textContent=Math.round(pts[119]).toLocaleString();
   api.$('[data-v]',el).innerHTML=cap<a?`<b>Workers are too slow.</b> They handle ${Math.round(cap)} msg/s but ${a} arrive: the backlog grows forever. You need at least ${Math.ceil(a*t/1000)} workers.`:pts[119]>0?'<b>Still draining.</b> Capacity is above the average, but the burst left a backlog. Add workers or accept the delay.':`<b>Keeps up.</b> ${mx>0?'The burst caused a temporary backlog that drained.':'No backlog.'} Utilisation ≈ ${Math.round(a/cap*100)}% outside the burst.`};
  el.addEventListener('input',draw);draw()}
}});
