COURSE.add({id:'s08',n:8,part:'A',track:'HLD',
title:'Reliability, load balancing, rate limiting and observability',
goal:'Keep a system up when parts fail, protect it from overload, and know when something is wrong.',
outcomes:['Turn an availability target into downtime and redundancy','Choose load-balancing and rate-limiting algorithms','Apply timeouts, retries, circuit breakers and bulkheads','Design a distributed rate limiter'],
concept:'reliability',
tasks:[{t:'Explain how a multi-region failover works, using the diagram.'},{t:'Compare four rate-limiting algorithms, including the window-boundary burst.',auto:'s08rl'},{t:'Break the system in the chaos lab and name the mechanism that helps each failure.',auto:'s08chaos'},{t:'Solve three production debugging scenarios.',auto:'s08dbg1'},{t:'Answer the rate-limiter interview checkpoint.',auto:'s08cp'},{t:'Rate yourself: can you explain circuit breakers and retry storms without notes?',auto:'s08sum'}],
modules:[
{title:'Warm-up: recall session 7',tab:'Warm-up',mins:10,out:'Recall quiz',blocks:[
 {t:'mcq',items:[
  {q:'Each message must reach email, analytics and ledger services. Use…',opts:['A job queue','Pub/sub'],a:1},
  {q:'A message fails 5 times. It should go to…',opts:['The dead-letter queue','/dev/null'],a:0},
  {q:'200 msg/s, 50 ms each. Minimum workers?',opts:['4','10','200'],a:1}]}]},

{title:'Availability: SLOs and redundancy',tab:'Availability',mins:25,out:'Availability of a design, computed',lead:'Availability is the share of time the system works. Each extra nine is about 10x harder.',blocks:[
 {t:'table',title:'The nines',head:['Availability','Downtime per year','Downtime per month'],rows:[['99%','3.65 days','7.3 hours'],['99.9%','8.8 hours','43.8 minutes'],['99.95%','4.4 hours','21.9 minutes'],['99.99%','52.6 minutes','4.4 minutes'],['99.999%','5.3 minutes','26 seconds']]},
 {t:'grid',title:'SLI, SLO, SLA',items:[
  {title:'SLI: what you measure',body:'e.g. share of requests answered successfully in under 300 ms.'},
  {title:'SLO: your target',body:'e.g. 99.9% of requests meet the SLI over 30 days. The gap (0.1%) is your error budget.'},
  {title:'SLA: the promise to customers',body:'A contract, usually looser than the SLO, with refunds if broken.'}]},
 {t:'lab',fn:'avail',title:'Lab · Availability calculator',intro:'Parts in a chain multiply their availability. Copies in parallel fail only if all fail at once.'},
 {t:'diagram',title:'Diagram · Multi-region failover',level:'i',nodes:['users@0,1:Users','dns@1,1:Geo DNS|health-checked','lb@2,0:Region A|active','region2@2,2:Region B|standby / active','db@3,0:Primary DB','replica@3,2:Replica'],edges:['users>dns','dns>lb','dns>region2','lb>db','region2>replica','db~>replica:async'],
  steps:[{hi:['users','dns','lb'],txt:'Normally geo-DNS sends users to Region A.'},{hi:['lb'],states:{lb:'down',db:'down'},txt:'Region A fails. Health checks to Region A start failing.'},{hi:['users','dns','region2'],states:{lb:'down',db:'down',region2:'new'},txt:'DNS stops returning Region A. Clients move as their DNS TTL expires (keep TTLs short: 30–60 s).'},{hi:['region2','replica'],states:{lb:'down',db:'down',replica:'new'},txt:'The replica in Region B is promoted. Writes not yet replicated are lost (RPO); time to recover is the RTO.'}]}]},

{title:'Load balancing and rate limiting',tab:'LB + rate limits',mins:25,out:'Pick algorithms with reasons',blocks:[
 {t:'table',title:'Load-balancing algorithms',head:['Algorithm','How','Good for'],rows:[
  ['Round robin','Next server in turn','Equal servers, short requests'],
  ['Least connections','Server with fewest open connections','Long or uneven requests (WebSockets, uploads)'],
  ['Weighted','Bigger servers get more','Mixed machine sizes, canary releases'],
  ['Hash (IP / user / key)','Same key → same server','Sticky sessions, local caches; use consistent hashing']]},
 {t:'grid',title:'Rate-limiting algorithms',items:[
  {title:'Token bucket',body:'Tokens refill at rate r up to capacity b; each request spends one. Allows short bursts up to b. Most common.'},
  {title:'Leaky bucket',body:'Requests queue and leave at a fixed rate. Smooth output; bursts wait or drop.'},
  {title:'Fixed window',body:'Count per minute. Simple, but 2x bursts at window edges.'},
  {title:'Sliding window log / counter',body:'Counts over the last 60 s exactly or approximately. Fair, more memory or maths.'}]},
 {t:'lab',fn:'bucket',title:'Lab · Token bucket',intro:'A client sends a burst. See which requests pass.'},
 {t:'diagram',title:'Diagram · Where the rate limiter sits',nodes:['client@0,1:Clients','gw@1,1:API gateway|rate limiter','cache@2,0:Redis|counters per key','api@2,1:API servers'],edges:['client>gw','gw>cache:check + count','gw>api:allowed','gw~>client:429 + Retry-After'],caption:'Counters live in a shared store so every gateway instance sees the same totals. Cost: a Redis call per request, and a decision about failing open or closed if Redis is down.'},
 {t:'ratelimit',id:'s08rl',concept:'ratelimit',title:'Lab · Four rate-limiting algorithms on the same traffic',level:'i',intro:'Start with request rate 10/s, capacity 20, refill 5/s. Press Play to watch the token bucket, then try the burst and window-boundary patterns.'}]},

{title:'Resilience patterns and observability',tab:'Resilience',mins:20,out:'Name the right pattern per failure',blocks:[
 {t:'cards',items:[
  {tag:'Timeouts',title:'Never wait forever',body:'<p>Every network call gets a timeout shorter than the caller\'s own deadline. Without one, slow dependencies use up all threads.</p>'},
  {tag:'Retries',title:'Retry carefully',body:'<p>Only idempotent calls, with backoff and jitter, and a retry budget (e.g. at most 10% extra traffic). Retrying at every layer multiplies load.</p>'},
  {tag:'Circuit breaker',title:'Stop calling a broken service',body:'<p>After many failures the breaker opens and calls fail fast for 30 s; then a few test calls decide whether to close it. Protects both sides.</p>'},
  {tag:'Bulkhead',title:'Separate pools',body:'<p>Give each dependency its own thread or connection pool, so a slow recommendations service cannot starve checkout.</p>'},
  {tag:'Degrade',title:'Serve less, not nothing',body:'<p>Show the page without recommendations; serve cached prices; turn off non-essential features under load (load shedding).</p>'},
  {tag:'Observe',title:'Metrics, logs, traces',body:'<p>Metrics (rates, errors, latency percentiles) for alerts; logs for detail; distributed traces to follow one request across services. Alert on symptoms users feel, not CPU.</p>'}]},
 {t:'mcq',items:[
  {q:'The recommendations service is slow and checkout threads all hang waiting for it.',opts:['Bulkhead + timeout','Bigger database'],a:0},
  {q:'The payment provider is returning errors for every call.',opts:['Retry immediately 10 times','Circuit breaker, show "try again later"'],a:1},
  {q:'You want to see which of 12 services made a request slow.',opts:['Distributed tracing','More CPU alerts'],a:0},
  {q:'Rolling out a risky change safely.',opts:['Canary to 1% then ramp','Deploy everywhere at once'],a:0}]},
 {t:'diagram',title:'Diagram · Retries, timeouts and a circuit breaker',nodes:['api@0,1:Checkout service','cb@1,1:Circuit breaker|closed → open → half-open','svc@2,1:Recommendation service','cache@1,2:Fallback|cached / default'],edges:['api>cb','cb>svc:calls with 300 ms timeout','cb>cache:when open'],
  steps:[{hi:['api','cb','svc'],txt:'<b>Closed:</b> calls pass through with a 300 ms timeout and at most 2 retries with backoff + jitter.'},{hi:['cb','svc'],states:{svc:'hot'},txt:'The service slows down. Without timeouts, checkout threads would pile up waiting: the failure spreads upstream.'},{hi:['cb','cache'],states:{svc:'hot',cb:'warn'},txt:'Errors exceed 50% in 10 s: the breaker <b>opens</b>. Calls fail fast and use the fallback (cached or generic recommendations).'},{hi:['cb','svc'],states:{cb:'warn'},txt:'After 30 s it goes <b>half-open</b>: a few trial calls. If they succeed it closes; if not it opens again.'}]},
 {t:'scalelab',id:'s08chaos',title:'Chaos lab · Break the system, then make it resilient',level:'i',system:'A healthy system at 10K req/s. Inject one failure at a time. Before reading the outcome, say what you expect. Then turn on <b>Timeouts + retries + circuit breaker</b> and repeat <b>Slow DB</b> and <b>Drop 20%</b>.',
  model:{readFrac:0.95,hitRate:0.9,jobsPerReq:0.2,workerCap:500},start:{ti:3,api:8,lb:true,cache:true,replicas:1,queue:true,workers:6},steps:[100,1000,5000,10000,20000],goal:20000,presets:false},
 {t:'predict',id:'s08dbg1',kind:'debug',title:'Debugging scenario · The retry storm',level:'x',scenario:'At 14:02 the database had a 10-second hiccup. It recovered at 14:02:10, but the site stayed down for 20 minutes.',metrics:[['Requests / s (normal)','10,000',''],['Requests / s (now)','42,000','bad'],['DB CPU','100%','bad'],['Error rate','65%','bad'],['Client retry policy','3 immediate retries','warn']],q:'What would you investigate and change?',
  opts:[['Retry amplification: add backoff + jitter, retry budgets and a circuit breaker',1,'Each failure triggered three instant retries from every layer, quadrupling load on a recovering database so it never caught up. Backoff, jitter and budgets let it recover.'],['Add more database replicas',0,'Replicas do not help the primary under a write/retry storm and take time to add.'],['Increase timeouts',0,'Longer timeouts hold more threads and connections.'],['Restart the database again',0,'The retry traffic would knock it over again.']],takeaway:'Retries can turn a 10-second blip into an outage. Retry with exponential backoff and jitter, cap retries per request, and stop retrying when a breaker is open.'},
 {t:'predict',id:'s08dbg2',kind:'debug',title:'Debugging scenario · Errors after a deploy',level:'i',scenario:'Error rate jumped from 0.1% to 6% at 10:15. Nothing else changed on the dashboards.',metrics:[['Error rate','6%','bad'],['Latency p99','210 ms','ok'],['CPU / memory','normal','ok'],['Deploy','v2.31 at 10:14','warn'],['Errors by server','only 3 of 10 servers','warn']],q:'What would you do first?',
  opts:[['Roll back v2.31 (or stop the canary), then investigate',1,'The errors started a minute after the deploy and only on servers running it. Restore service first; debug from logs afterwards.'],['Add more servers',0,'Capacity is fine: CPU and latency are normal.'],['Clear the cache',0,'No evidence points to the cache, and a cold cache would add load.'],['Wait to see if it recovers',0,'6% of users are failing now.']],takeaway:'Correlate with changes. Mitigate first (rollback), diagnose second. Canary deploys limit the blast radius.'},
 {t:'predict',id:'s08dbg3',kind:'debug',title:'Debugging scenario · Everything is green, but orders are late',level:'i',scenario:'Customers say order confirmation emails arrive hours late. Every service health check is green.',metrics:[['API error rate','0.05%','ok'],['API p99','150 ms','ok'],['Queue depth','1.2 M','bad'],['Oldest message age','3 h 10 min','bad'],['Email workers running','2 of 20','warn']],q:'What is the problem, and what was missing from monitoring?',
  opts:[['Workers crashed; alert on queue age and consumer count',1,'The queue absorbed the failure silently: producers were healthy. Monitor the age of the oldest message and the number of active consumers, not just API health.'],['The email provider is slow',0,'Possible, but 18 of 20 workers are missing: check them first.'],['The API is overloaded',0,'API latency and errors are normal.']],takeaway:'Asynchronous systems fail quietly. Watch queue depth, oldest-message age and consumer count as first-class signals.'},
 {t:'diagram',title:'Diagram · Observability: metrics, logs and traces',nodes:['api@0,1:API servers','svc@1,1:Order service','db@2,1:Database','mon@1,0:Metrics · logs · traces|dashboards + alerts'],edges:['api>svc:trace id','svc>db','api~>mon','svc~>mon','db~>mon'],caption:'Metrics say <i>that</i> something is wrong (rates, errors, durations, saturation). Traces say <i>where</i> (which hop is slow). Logs say <i>why</i>. Alert on user-facing symptoms (SLOs), investigate with the rest.'}]},

{title:'Guided problem: a distributed rate limiter',tab:'Guided problem',mins:30,out:'Rate limiter design',lead:'Prompt: <b>"Design a rate limiter for a public API: 100 requests per minute per API key, across 50 API servers."</b>',blocks:[
 {t:'stepper',steps:[
  {title:'Clarify',short:'Clarify',secs:120,think:'Where does it run? How strict? What happens over the limit?',answer:'Runs before the API logic (gateway or middleware). Limits per API key, some per IP. Slight over-counting is OK; under-counting a little at the edges is OK. Over limit: 429 with Retry-After. Must add < 2 ms latency and not become a single point of failure.'},
  {title:'Algorithm',short:'Algorithm',secs:150,think:'Which algorithm, and why?',answer:'Token bucket per key: allows small bursts, one counter + timestamp per key, cheap to compute. (Sliding-window counter is a fine alternative.)'},
  {title:'Where is the state?',short:'State',secs:180,think:'50 servers. Each counting alone means a key can get 50x the limit. Options?',answer:'<ul class="clean"><li><b>Shared Redis</b>: one atomic script per request (read tokens, refill, decrement). Accurate; adds ~1 ms; Redis must be highly available (replicas, cluster sharded by key).</li><li><b>Local + sync</b>: each server keeps local buckets and syncs to Redis every 100 ms. Faster, slightly inaccurate.</li><li><b>Sticky routing</b>: hash the key to one server. Simple, but uneven load.</li></ul>'},
  {title:'Failures',short:'Failures',secs:150,think:'Redis is down. Fail open or fail closed?',answer:'Usually <b>fail open</b> (allow traffic, use local approximate limits) so a limiter outage does not take the API down. Fail closed only for abuse-sensitive endpoints like login or SMS sending.'},
  {title:'Challenge',short:'Challenge',secs:150,think:'Enterprise customers want 10,000/min and different limits per endpoint.',answer:'Store rules in a config table (key, endpoint, rate, burst) cached in each server and refreshed every minute; bucket key = apiKey + endpoint. Big customers might get a dedicated limit pool.'}]}]},

{title:'Review',tab:'Review',mins:10,out:'Flashcards + homework',blocks:[
 {t:'flash',items:[['99.9% per month?','About 43 minutes of downtime.'],['Two 99.9% parts in series?','≈ 99.8%.'],['Two 99% copies in parallel?','99.99%.'],['Token bucket allows…','Bursts up to the bucket size, then the refill rate.'],['Circuit breaker states?','Closed → open (fail fast) → half-open (test) → closed.'],['Fail open or closed?','Open for most rate limiters; closed for abuse-sensitive actions.']]},
 {t:'task',title:'Homework',items:['Write the SLOs (2) and alerts (3) for a food-delivery checkout API.']},
 {t:'checkpoint',id:'s08cp',concept:'ratelimit',title:'Interview checkpoint',prompt:'"Design a rate limiter for a public API: 100 requests per minute per API key, across 50 gateway servers."',steps:['Clarify the limit, the key (API key / user / IP) and burst tolerance','Choose an algorithm and justify it (token bucket / sliding window)','Store counters centrally (Redis) with atomic operations','Explain the window-boundary problem and how you avoid it','Return 429 with Retry-After and rate-limit headers','Decide fail-open vs fail-closed when Redis is down','Handle hot keys and latency (local pre-check, sharded counters)','Multi-region: per-region limits or eventual global sync'],
  model:'Token bucket per API key in Redis, updated atomically with a Lua script (refill by elapsed time, then take a token). Gateways call Redis per request; responses carry X-RateLimit-Remaining and Retry-After. If Redis is down, fail open for most APIs (availability) but closed for expensive ones. Very hot keys get a local token cache refreshed in batches.',followups:[['"Why not a fixed window?"','A burst at 0:59 and another at 1:01 lets 2× the limit through in two seconds.'],['"How do you make the Redis update atomic?"','A Lua script or MULTI/EXEC so read-refill-decrement happens as one step.']]},
 {t:'recall',title:'Active recall',items:[['What does a circuit breaker do?','Stops calling a failing dependency for a while, fails fast with a fallback, then tests recovery with a few calls.'],['Why can retries be dangerous?','They multiply load on a struggling system (retry storms) and can duplicate effects. Use backoff, jitter, budgets and idempotency.'],['Token bucket vs fixed window?','Token bucket allows controlled bursts up to the bucket size; a fixed window can let 2× through at window boundaries.','ratelimit'],['What is the difference between RPO and RTO?','RPO: how much data you can lose. RTO: how long recovery may take.'],['Which signals reveal a silently failing queue?','Queue depth, oldest-message age and active consumer count.']]},
 {t:'summary',id:'s08sum',title:'Session summary',learned:['<b>Why resilience patterns exist:</b> failures spread through waiting callers','<b>When to use them:</b> every network call gets a timeout; retries only for idempotent operations','<b>When not to retry:</b> non-idempotent calls without keys, or when a breaker is open','<b>Trade-offs:</b> fail open vs closed, freshness vs fallback, cost of redundancy','<b>Interview questions:</b> rate limiter design, SLOs, failover, debugging from metrics'],explain:'Walk through what happens when a dependency slows to 2 s, with and without timeouts and a circuit breaker.'}]}
],
labs:{
 avail(el,api){
  const parts=[['Load balancer',99.99,2],['App servers',99.5,3],['Cache',99.9,1],['Database',99.95,2]];
  el.innerHTML=`<div class="tbl"><table><thead><tr><th>Part (in series)</th><th>Availability of one copy (%)</th><th>Copies in parallel</th><th>Part availability</th></tr></thead><tbody>${parts.map((p,i)=>`<tr><td>${p[0]}</td><td><input type="number" step="0.01" min="90" max="99.999" value="${p[1]}" data-a="${i}" style="max-width:110px"></td><td><input type="number" min="1" max="5" value="${p[2]}" data-c="${i}" style="max-width:80px"></td><td class="mono" data-pa="${i}"></td></tr>`).join('')}</tbody></table></div><div class="out"><div><b data-tot></b><span>whole system</span></div><div><b data-down></b><span>downtime per year</span></div><div><b data-mon></b><span>downtime per month</span></div></div><div class="verdict" data-v></div>`;
  const draw=()=>{let tot=1;let worst=null,wv=2;parts.forEach((p,i)=>{const a=Math.min(99.9999,+api.$(`[data-a="${i}"]`,el).value||0)/100,c=Math.max(1,+api.$(`[data-c="${i}"]`,el).value||1);const pa=1-Math.pow(1-a,c);tot*=pa;if(pa<wv){wv=pa;worst=p[0]}api.$(`[data-pa="${i}"]`,el).textContent=(pa*100).toFixed(4)+'%'});
   const down=(1-tot)*365*24;api.$('[data-tot]',el).textContent=(tot*100).toFixed(3)+'%';api.$('[data-down]',el).textContent=down>=24?(down/24).toFixed(1)+' days':down>=1?down.toFixed(1)+' h':(down*60).toFixed(0)+' min';api.$('[data-mon]',el).textContent=((1-tot)*30*24*60).toFixed(0)+' min';
   api.$('[data-v]',el).innerHTML=`The weakest part is <b>${worst}</b>. A chain is never more available than its weakest link: adding copies there helps most. Note this assumes copies fail independently; a shared power supply or a bad deploy breaks that assumption.`};
  el.addEventListener('input',draw);draw()},
 bucket(el,api){
  el.innerHTML=`<div class="form"><label>Bucket size (burst): <b data-bv></b><input type="range" min="1" max="20" value="5" data-b></label><label>Refill (tokens/s): <b data-rv></b><input type="range" min="1" max="10" value="2" data-r></label><label>Pattern<select data-p><option value="burst">15 requests at once, then 1/s</option><option value="steady">4 requests every second</option><option value="spiky">Bursts of 8 every 3 s</option></select></label></div><div data-row style="display:flex;flex-wrap:wrap;gap:3px"></div><div class="out"><div><b data-ok></b><span>allowed</span></div><div><b data-no></b><span>rejected (429)</span></div></div><div class="verdict" data-v></div>`;
  const draw=()=>{const B=+api.$('[data-b]',el).value,r=+api.$('[data-r]',el).value,p=api.$('[data-p]',el).value;api.$('[data-bv]',el).textContent=B;api.$('[data-rv]',el).textContent=r;
   const times=[];if(p==='burst'){for(let i=0;i<15;i++)times.push(0);for(let s=1;s<=10;s++)times.push(s)}else if(p==='steady'){for(let s=0;s<10;s++)for(let k=0;k<4;k++)times.push(s+k*.25)}else{for(let s=0;s<10;s+=3)for(let k=0;k<8;k++)times.push(s)}
   let tok=B,last=0,ok=0,no=0;const cells=times.map(t=>{tok=Math.min(B,tok+(t-last)*r);last=t;if(tok>=1){tok-=1;ok++;return [t,1]}no++;return [t,0]});
   api.$('[data-row]',el).innerHTML=cells.map(c=>`<span title="t=${c[0]}s" style="width:20px;height:28px;border-radius:3px;background:${c[1]?'var(--good)':'var(--marker)'};display:grid;place-items:center;color:#fff;font-size:9px;font-family:var(--f-mono)">${Math.floor(c[0])}</span>`).join('');
   api.$('[data-ok]',el).textContent=ok;api.$('[data-no]',el).textContent=no;api.$('[data-v]',el).innerHTML=`Each square is one request (number = second it arrived; green allowed, red 429). The first ${B} of a burst pass using saved tokens; after that only ${r} per second get through.`};
  el.addEventListener('input',draw);el.addEventListener('change',draw);draw()}
}});
