COURSE.add({id:'s10',n:10,part:'B',track:'HLD',
title:'Case study: a chat app like WhatsApp',
goal:'Design real-time messaging: long-lived connections, delivery to online and offline users, ordering, groups and presence.',
outcomes:['Explain why chat needs persistent connections and a connection registry','Store and order messages per conversation','Deliver to offline users and to large groups','Handle receipts, multiple devices and gateway failures'],
concept:'realtime',
tasks:[{t:'Estimate concurrent connections and messages per second for the chat app.',auto:'s10cap'},{t:'Trace a message from sender to an online and an offline receiver.',auto:'s10trace'},{t:'Predict what happens when a WebSocket server restarts.',auto:'s10ws'},{t:'Design WhatsApp yourself, then compare with the reference.',auto:'s10build'},{t:'Answer the chat interview checkpoint.',auto:'s10cp'},{t:'Rate yourself: can you explain message delivery to offline users without notes?',auto:'s10sum'}],
modules:[
{title:'Warm-up: real-time building blocks',tab:'Warm-up',mins:10,out:'Recall quiz',blocks:[
 {t:'mcq',items:[
  {q:'Server needs to push messages instantly. Use…',opts:['Polling every minute','WebSocket'],a:1},
  {q:'Shard key for chat messages?',opts:['message_id','conversation_id'],a:1},
  {q:'Ordering is usually guaranteed…',opts:['Globally','Per conversation (per partition)'],a:1}]}]},

{title:'Clarify and estimate',tab:'Clarify',mins:15,out:'Scope + numbers',lead:'Prompt: <b>"Design a chat app like WhatsApp."</b>',blocks:[
 {t:'stepper',steps:[
  {title:'Scope',secs:150,think:'Which features are in? Which are out?',answer:'<p><b>In:</b> 1:1 chat, groups up to 500, delivered/read receipts, online status, offline delivery with push notifications, multiple devices per user, history kept.</p><p><b>Out:</b> voice/video calls, payments, stories. End-to-end encryption mentioned but not designed.</p><p><b>Never-happen:</b> a message lost after the sender sees one tick; messages shown out of order within a chat.</p>'},
  {title:'Estimate',secs:150,think:'500 M daily users, 40 messages each, 100 bytes average. Messages/s? Storage/day? Open connections?',answer:'<ul class="clean"><li>20 B messages/day ≈ <b>230 K/s</b> average, ~700 K/s peak.</li><li>20 B × 100 B ≈ <b>2 TB/day</b> of text (media separately in object storage).</li><li>Maybe 100 M+ connections open at once; at ~100 K connections per gateway server ≈ <b>1,000+ gateway servers</b>.</li></ul><p>Conclusion: write-heavy, needs a horizontally scaled message store and a large fleet of connection servers.</p>'}]},
 {t:'capacity',id:'s10cap',title:'Estimation · Chat at scale',level:'f',scenarios:[{name:'Chat app',dau:50e6,rpu:40,ratio:2,obj:300,peak:2.5}],ask:['reqDay','qps','peak','storageDay','storageYear']}]},

{title:'Guided design',tab:'Guided design',mins:45,out:'Architecture + message flow',blocks:[
 {t:'diagram',id:'s10trace',title:'Diagram · Delivering a message over WebSockets',level:'i',nodes:['alice@0,0:Alice|online','ws1@1,0:WS server 1','chat@2,1:Chat service','db@3,1:Message store|per conversation','reg@2,0:Presence / session map|user → server','ws2@1,2:WS server 2','bob@0,2:Bob','push@3,2:Push service|APNs / FCM'],edges:['alice<>ws1','ws1>chat','chat>db:1. store','chat>reg:2. where is Bob?','chat>ws2:3a. online','ws2<>bob','chat>push:3b. offline'],
  steps:[{hi:['alice','ws1','chat'],txt:'Alice’s message travels over her open WebSocket to the chat service.'},{hi:['chat','db'],txt:'Store first (durable), then acknowledge: Alice sees one tick ✓.'},{hi:['chat','reg'],txt:'Look up which WebSocket server holds Bob’s connection.'},{hi:['chat','ws2','bob'],txt:'Bob is online: push it down his connection; his app acks → two ticks ✓✓.'},{hi:['chat','push'],states:{bob:'dim',ws2:'dim'},txt:'If Bob is offline, send a push notification. When he reconnects, he fetches messages after his last-seen message id.'}]},
 {t:'predict',id:'s10ws',title:'What happens next?',level:'i',scenario:'Each WebSocket server holds 100 K open connections. You deploy a new version and restart one server.',q:'What happens, and what should you design for?',
  opts:[['100 K clients reconnect at once: use jittered reconnect backoff and drain servers gradually',1,'All clients reconnect within seconds and stampede the remaining servers and the auth/presence services. Drain connections slowly before shutdown and make clients reconnect with random backoff.'],['Nothing: the load balancer handles it',0,'The load balancer re-routes, but the reconnect burst still hits everything behind it.'],['Messages are lost',0,'Messages are stored before acknowledgement; clients re-sync from their last message id.'],['Users must log in again',0,'Tokens survive; only the connection is new.']],takeaway:'Stateful connections make deploys and failures bursty. Plan for reconnect storms.'},
 {t:'stepper',steps:[
  {title:'APIs and connection',short:'APIs',secs:150,think:'What runs over HTTP and what over the WebSocket?',answer:'<p><b>WebSocket</b> (persistent): <code>send {clientMsgId, chatId, body}</code>, server pushes <code>message</code>, <code>ack</code>, <code>receipt</code>, <code>presence</code> events.</p><p><b>HTTP</b>: login, <code>GET /chats/{id}/messages?before=</code> for history, media upload (returns a URL sent as a message).</p><p><code>clientMsgId</code> makes resends idempotent.</p>'},
  {title:'Data',short:'Data',secs:180,think:'Message table shape, keys and store type.',answer:'<p><b>Message</b>(chatId, seq, msgId, senderId, body, sentAt) with partition key <b>chatId</b> and sort key <b>seq</b>: a wide-column store (Cassandra-style) for huge write volume and "latest N messages of a chat" reads.</p><p><b>Chat</b>(chatId, members), <b>UserChats</b>(userId → chats + last read seq), <b>Receipt</b>(chatId, userId, deliveredSeq, readSeq).</p><p><b>seq</b> is assigned per chat by the chat service: this is what gives ordering.</p>'},
  {title:'Message flow',short:'Flow',secs:180,think:'Alice sends "hi" to Bob. List every hop until Bob sees it and Alice sees two ticks.',answer:'<ol><li>Alice\'s app → her gateway over WebSocket.</li><li>Gateway → chat service: assign seq, store the message, ack Alice (one tick).</li><li>Chat service looks up Bob in the connection registry: which gateway holds his socket?</li><li>If online: forward to that gateway → Bob\'s app → Bob\'s app sends "delivered" → Alice gets two ticks.</li><li>If offline: send a push notification; Bob\'s app fetches missed messages (seq > last seen) when it reconnects.</li></ol>'},
  {title:'Design and break it',short:'Design lab',secs:300,think:'Add the parts, then break things.',blocks:[{t:'arch',title:'Chat system lab',w:760,h:340,
   nodes:[{id:'a',x:20,y:50,w:110,label:'Alice app',sub:'WebSocket'},{id:'b',x:20,y:250,w:110,label:'Bob app',sub:'WebSocket'},{id:'gw',x:175,y:150,w:130,label:'WS gateways ×N',sub:'hold connections'},{id:'chat',x:350,y:150,w:135,label:'Chat service',sub:'seq, store, route'},{id:'store',x:560,y:30,w:180,label:'Message store',sub:'partitioned by chatId'},{id:'reg',x:560,y:130,w:180,label:'Connection registry',sub:'user → gateway, online',opt:'reg'},{id:'q',x:350,y:260,w:135,h:52,label:'Fan-out queue',sub:'group delivery',opt:'q'},{id:'push',x:560,y:250,w:180,label:'Push service',sub:'APNs / FCM',opt:'push'}],
   edges:[{d:'M130 78H150V165H175'},{d:'M175 192H150V278H130'},{d:'M305 178H350'},{d:'M485 165H520V58H560',label:'store',lx:492,ly:110},{d:'M485 178H560',opt:'reg',label:'lookup',lx:500,ly:172},{d:'M417 206V260',opt:'q'},{d:'M485 192H520V278H560',opt:'push',label:'offline',lx:492,ly:236}],
   toggles:[{id:'reg',label:'Connection registry'},{id:'push',label:'Push notifications'},{id:'q',label:'Group fan-out queue'}],
   fails:[
    {label:'Bob is on another gateway server',run:o=>o.reg?{lvl:'ok',oks:['reg'],txt:'The registry says Bob is on gateway #417; the chat service forwards there. Without it you would broadcast to all 1,000 gateways.'}:{lvl:'bad',hits:['gw'],txt:'The chat service does not know which of 1,000 gateways holds Bob\'s socket. Broadcasting to all of them does not scale. Add a connection registry.'}},
    {label:'Bob is offline',run:o=>o.push?{lvl:'ok',oks:['push','store'],txt:'Message is stored; a push notification wakes Bob\'s phone; on reconnect the app fetches messages with seq > its last seen seq.'}:{lvl:'warn',hits:['b'],txt:'The message is stored, but Bob is never told. He sees it only when he opens the app. Add push notifications.'}},
    {label:'Message to a 500-member group',run:o=>o.q?{lvl:'ok',oks:['q'],txt:'Store once; fan-out workers deliver to each online member\'s gateway and push to offline ones, in parallel, without slowing the sender.'}:{lvl:'warn',hits:['chat'],txt:'The chat service loops over 500 members inline: the sender waits and the service ties up. Store once and fan out via a queue.'}},
    {label:'A gateway server crashes',run:o=>({lvl:'warn',hits:['gw'],txt:'~100 K users lose their sockets. Apps reconnect (with jittered backoff) to other gateways, update the registry, and fetch missed messages by seq. Unacked sends are resent with the same clientMsgId, so no duplicates.'})},
    {label:'One message-store partition is down',run:o=>({lvl:'warn',hits:['store'],txt:'Chats on that partition cannot store new messages; replicas (e.g. 3 copies, quorum writes) let one node fail without impact. Clients keep unsent messages and retry.'})}],
   start:'Start with only gateways, chat service and the message store. Add the registry, push and fan-out queue when a failure demands them.'}]},
  {title:'Challenge',short:'Challenge',secs:180,think:'Bob uses a phone and a laptop. What changes?',answer:'The registry maps a user to a <b>list</b> of connections (deviceId → gateway). Deliver to every device; track delivered/read per device; the read pointer syncs so reading on the laptop clears the phone\'s badge. With end-to-end encryption, each device has its own key and the sender encrypts per device.'}]}]},

{title:'Deep dives: ordering, receipts, presence, media',tab:'Deep dives',mins:30,out:'Answers to 6 deep dives',blocks:[
 {t:'cards',items:[
  {tag:'Ordering',title:'Per chat, by sequence',body:'<p>The chat service (or the partition leader for that chat) assigns an increasing seq. Clients sort by seq, not by phone clocks. Messages sent "at the same time" get a definite order.</p>'},
  {tag:'Receipts',title:'Pointers, not per-message rows',body:'<p>Store "delivered up to seq 120, read up to seq 115" per user per chat. One update covers many messages.</p>'},
  {tag:'Presence',title:'Heartbeats with TTL',body:'<p>Apps send a heartbeat every ~30 s; presence entries expire if heartbeats stop. Publish online/offline changes only to people with that chat open; it is a hint, so eventual consistency is fine.</p>'},
  {tag:'Media',title:'Upload separately',body:'<p>The app uploads the photo to object storage (pre-signed URL), then sends a small message containing the URL and a thumbnail. Media is served through a CDN.</p>'},
  {tag:'History',title:'Recent hot, old cold',body:'<p>Recent messages in the fast store; very old ones can move to cheaper storage. Or, like WhatsApp, keep history mainly on devices and the server only until delivered.</p>'},
  {tag:'Search',title:'Separate index',body:'<p>Full-text search needs an inverted index built asynchronously from message events, per user. With end-to-end encryption, search happens on the device.</p>'}]},
 {t:'drill',title:'Failure drill',prefix:'What happens if… ',button:'Draw a failure',items:[['the phone loses network for 2 hours?','Messages queue on the phone (pending, one grey tick); on reconnect it resends with the same clientMsgIds and fetches missed messages by seq.'],['the same message arrives at the server twice?','The server keeps (chatId, clientMsgId) and ignores the duplicate, returning the original seq.'],['the registry is stale and points to a dead gateway?','Forward fails; mark user offline; send push; registry entries also expire by TTL.'],['a group gets 200 messages per second?','Batch deliveries per member; rate limit; consider marking it a "broadcast channel" with pull-based reading.']]},
 {t:'builder',id:'s10build',title:'Design it yourself · WhatsApp',level:'x',reqs:['1:1 and group chats (up to 256 members)','Messages delivered instantly to online users, later to offline users','Never lose a message the sender saw as sent','Photos and videos','50 M daily users, ~2 B messages/day'],palette:['client','lb','ws','api','db:Wide-column store','cache','queue','worker','obj','cdn','provider:Push provider','kafka'],
  ref:{nodes:['client@0,1','lb@1,1','ws@2,1:WebSocket servers','cache@3,0:Presence / session map','db@3,1:Message store|by conversation','queue@2,2:Queue','worker@3,2:Push / fan-out workers','provider@4,2:Push provider','obj@4,1:Object storage|media'],edges:['client>lb','lb>ws','ws>cache','ws>db','ws>queue','queue>worker','worker>provider','client~>obj:media upload'],
   need:{lb:'Spreads millions of long-lived connections.',ws:'Holds open connections so the server can push instantly.',db:'Durable message store partitioned by conversation, ordered by time.',cache:'Which server holds each user’s connection, plus presence.',queue:'Decouples group fan-out and offline push from the send path.',worker:'Fan out to group members and send push notifications.',provider:'Wakes offline phones (APNs/FCM).',obj:'Photos and videos are uploaded once and referenced by id.'},
   optional:{cdn:'Popular media in groups; also speeds up downloads far away.',kafka:'A log instead of a queue if many consumers need the message stream (search, backups).',api:'Plain HTTP endpoints for history sync and media upload URLs.'},
   whyNot:{},tradeoffs:'Store-then-ack gives durability at the cost of a little latency. Group fan-out on write is simple for small groups; very large groups need fan-out on read. Ordering per conversation via sequence numbers, not clocks.'}}]},

{title:'Review',tab:'Review',mins:20,out:'Rubric + homework',blocks:[
 {t:'flash',items:[['Why a connection registry?','To find which gateway holds a user\'s socket.'],['Ordering source?','A per-chat sequence number assigned by the server.'],['Offline delivery?','Store, push notify, fetch by seq on reconnect.'],['Group fan-out?','Store once, deliver via async workers.'],['Read receipts storage?','Per user per chat: delivered/read up to seq N.'],['Presence?','Heartbeats + TTL; eventually consistent hint.']]},
 {t:'rubric',title:'Score yourself on this case',rows:[['Clarify','Scope, scale, never-happen rules'],['Interactions','WebSocket vs HTTP split, idempotent sends'],['Data','Partition by chat, seq ordering'],['Design','Gateways, registry, store, push'],['Challenge','Offline, groups, gateway crash'],['Communication','Clear message-flow trace']]},
 {t:'task',title:'Homework',items:['Write the message flow for a group message with 3 online and 2 offline members, including receipts.']},
 {t:'checkpoint',id:'s10cp',title:'Interview checkpoint',prompt:'"Design WhatsApp. Start with how one message gets from Alice to Bob."',steps:['Clarify 1:1 vs groups, online/offline, media, receipts','Estimate connections and messages per second','Choose WebSockets for push; explain why not polling','Store before acknowledging (durability)','Route to the receiver’s connection via a session map','Handle offline users: push + sync on reconnect','Order messages per conversation (sequence numbers)','Discuss reconnect storms, group fan-out and media'],
  model:'Clients keep a WebSocket to a gateway. Send → chat service stores in a store partitioned by conversation (sequence number) → ack ✓ → look up receiver’s gateway → push → receiver ack ✓✓. Offline: push notification; client syncs from its last sequence number. Groups: fan out via queue workers. Media to object storage, message holds the URL.',followups:[['"Messages arrive out of order."','Per-conversation sequence numbers assigned by the server; clients sort and request gaps.'],['"A gateway dies."','Clients reconnect elsewhere with jittered backoff and re-sync; nothing is lost because messages were stored before ack.']]},
 {t:'recall',title:'Active recall',items:[['Why WebSockets for chat?','The server must push messages instantly; polling is late and wasteful.'],['When does the sender see one tick?','After the server has durably stored the message.'],['How does an offline user get messages?','A push notification wakes the app; it syncs messages after its last seen sequence number.'],['Why store messages by conversation?','The main read is "messages in this chat, in order": one partition per conversation.'],['What is a reconnect storm?','Many clients reconnecting at once after a server restart; mitigate with jittered backoff and draining.']]},
 {t:'summary',id:'s10sum',title:'Session summary',learned:['<b>Why push connections exist:</b> instant delivery without polling','<b>When to fan out on write:</b> small groups; on read for huge ones','<b>When not to use WebSockets:</b> rare updates or on-demand data','<b>Trade-offs:</b> stateful servers, ordering, durability vs latency','<b>Interview questions:</b> receipts, presence, offline delivery, media'],explain:'Explain how a message reaches an offline user and how ordering is preserved.'}]}
]});
