COURSE.add({id:'s11',n:11,part:'B',track:'HLD',
title:'Case study: a news feed like Instagram',
goal:'Design a read-heavy social feed: posting media, following people, and building each user\'s feed fast, including for celebrities.',
outcomes:['Store and serve photos with object storage and a CDN','Compare fan-out on write, fan-out on read and the hybrid','Size the fan-out cost with numbers','Paginate and rank a feed'],
modules:[
{title:'Warm-up',tab:'Warm-up',mins:10,out:'Recall quiz',blocks:[
 {t:'mcq',items:[
  {q:'Photos should be stored in…',opts:['The posts table','Object storage, served by a CDN'],a:1},
  {q:'Feed pagination that survives new posts?',opts:['Offset','Cursor'],a:1},
  {q:'A queue between the post service and feed builders helps because…',opts:['It absorbs bursts and decouples work','It makes posting synchronous'],a:0}]}]},

{title:'Clarify and estimate',tab:'Clarify',mins:15,out:'Scope + numbers',lead:'Prompt: <b>"Design Instagram\'s home feed."</b>',blocks:[
 {t:'stepper',steps:[
  {title:'Scope',secs:150,think:'Must-haves and quality targets?',answer:'<p><b>In:</b> post a photo with caption; follow/unfollow; home feed of followed accounts, newest or ranked; likes and comment counts. <b>Out:</b> stories, reels, DMs, search.</p><p><b>Quality:</b> feed loads in < 300 ms; a new post may take a few seconds to appear (eventual is fine); photos never lost.</p>'},
  {title:'Estimate',secs:150,think:'500 M daily users, 2 posts/day per 10 users, 10 feed opens/day each, 200 follows average, 2 MB per photo.',answer:'<ul class="clean"><li>Posts: 100 M/day ≈ <b>1,200/s</b>.</li><li>Feed reads: 5 B/day ≈ <b>58,000/s</b> → strongly read-heavy.</li><li>Photo storage: 100 M × 2 MB = <b>200 TB/day</b> (plus resized copies) → object storage + CDN.</li><li>Fan-out on write: 1,200 posts/s × 200 followers = <b>240,000 feed inserts/s</b>.</li></ul>'}]}]},

{title:'Guided design',tab:'Guided design',mins:40,out:'Architecture with fan-out choice',blocks:[
 {t:'stepper',steps:[
  {title:'APIs and data',short:'APIs + data',secs:180,think:'List APIs and tables.',answer:'<p><code>POST /media</code> → pre-signed upload URL · <code>POST /posts {mediaId, caption}</code> · <code>POST /users/{id}/follow</code> · <code>GET /feed?cursor=</code>.</p><p><b>Post</b>(postId, authorId, mediaUrl, caption, createdAt) partitioned by authorId · <b>Follow</b>(followerId, followeeId) both directions indexed · <b>FeedCache</b>: per user, a list of the latest ~500 postIds in Redis.</p>'},
  {title:'Two ways to build a feed',short:'Fan-out',secs:240,think:'Push (on write) or pull (on read)? Write down one benefit and one cost each.',answer:'<div class="tbl"><table><thead><tr><th></th><th>Fan-out on write (push)</th><th>Fan-out on read (pull)</th></tr></thead><tbody><tr><td>When a user posts</td><td>Insert postId into every follower\'s feed list</td><td>Only store the post</td></tr><tr><td>When a user opens the feed</td><td>Read one precomputed list: very fast</td><td>Fetch recent posts of all 200 followees and merge: slow</td></tr><tr><td>Breaks on</td><td>Celebrities with 50 M followers</td><td>Users following thousands of accounts</td></tr></tbody></table></div><p><b>Hybrid</b> (what large systems do): push for normal authors; for celebrities, skip the push and merge their recent posts in at read time.</p>'},
  {title:'Design and break it',short:'Design lab',secs:300,think:'Add parts and break things.',blocks:[{t:'arch',title:'Feed system lab',w:760,h:340,
   nodes:[{id:'app',x:20,y:140,w:110,label:'Mobile app'},{id:'cdn',x:20,y:260,w:110,label:'CDN',sub:'photos',opt:'cdn'},{id:'post',x:180,y:60,w:140,label:'Post service'},{id:'feed',x:180,y:220,w:140,label:'Feed service',sub:'read + merge'},{id:'obj',x:380,y:20,w:150,label:'Object storage',sub:'photos'},{id:'pdb',x:380,y:100,w:150,label:'Posts DB',sub:'by authorId'},{id:'q',x:380,y:180,w:150,h:52,label:'Fan-out queue',opt:'push'},{id:'fw',x:580,y:180,w:160,h:52,label:'Fan-out workers',sub:'skip celebrities',opt:'push'},{id:'fc',x:580,y:270,w:160,label:'Feed cache',sub:'postIds per user',opt:'push'},{id:'graph',x:580,y:60,w:160,label:'Follow graph',sub:'who follows whom'}],
   edges:[{d:'M130 160H155V88H180'},{d:'M130 176H155V248H180'},{d:'M320 74H350V48H380'},{d:'M320 92H380'},{d:'M320 104H350V206H380',opt:'push',label:'new post',lx:326,ly:150},{d:'M530 206H580',opt:'push'},{d:'M660 116V180',opt:'push',dash:true,arrow:false},{d:'M660 232V270',opt:'push'},{d:'M320 260H560V298H580',opt:'push',label:'read list',lx:420,ly:254},{d:'M320 240H350V128H380',opt:'!push',label:'query each followee',lx:326,ly:170},{d:'M75 260V196',opt:'cdn',dash:true,arrow:false}],
   toggles:[{id:'cdn',label:'CDN for photos'},{id:'push',label:'Fan-out on write + feed cache'},{id:'hybrid',label:'Hybrid: pull celebrities at read time'}],
   fails:[
    {label:'Normal user opens the feed',run:o=>o.push?{lvl:'ok',oks:['fc','feed'],txt:'One read of a precomputed list of postIds, then a batch fetch of those posts (mostly cached): tens of milliseconds.'}:{lvl:'warn',hits:['pdb','feed'],txt:'Pull model: query recent posts of ~200 followees and merge. Many reads per feed open × 58,000 opens/s. Slow and expensive.'}},
    {label:'Celebrity with 50 M followers posts',run:o=>o.push&&!o.hybrid?{lvl:'bad',hits:['fw','fc'],txt:'Fan-out workers must write 50 M feed entries for one post. Minutes of lag, a huge write spike, and it repeats with every celebrity post.'}:o.push&&o.hybrid?{lvl:'ok',oks:['feed','pdb'],txt:'Celebrity posts are not pushed. At read time the feed service merges the few celebrities a user follows (their recent posts are heavily cached) into the precomputed list.'}:{lvl:'ok',txt:'In the pull model nothing happens at post time, so celebrities are cheap to post, but every feed read is expensive.'}},
    {label:'A photo goes viral',run:o=>o.cdn?{lvl:'ok',oks:['cdn'],txt:'The CDN edges serve it; object storage sees one request per edge.'}:{lvl:'bad',hits:['obj'],txt:'Every view downloads from object storage in one region: high latency far away and a big bandwidth bill. Add a CDN.'}},
    {label:'A feed-cache node is lost',run:o=>o.push?{lvl:'warn',hits:['fc'],txt:'Those users\' lists are gone. Rebuild on demand by pulling recent posts from followees (slower first load), then refill. Cache replicas reduce this.'}:{lvl:'ok',txt:'No feed cache in the pull model.'}},
    {label:'User follows someone new',run:o=>({lvl:'ok',oks:['graph'],txt:'Write the edge; backfill that person\'s last few posts into the follower\'s list asynchronously. A few seconds of delay is acceptable.'})}],
   start:'Start in the pull model with no CDN. Turn on fan-out, then break it with a celebrity, then add the hybrid.'}]},
  {title:'Challenge',short:'Challenge',secs:180,think:'Product wants a ranked feed instead of newest-first.',answer:'Candidate generation (the precomputed list + celebrity posts, ~500) → ranking service scores each with a model (likes, relationship, recency) → return top 20 with a cursor. Cache the ranked page briefly. Cost: more computation per open; must stay inside the latency budget.'}]}]},

{title:'Lab: the cost of fan-out',tab:'Fan-out lab',mins:25,out:'Pick a celebrity threshold with numbers',lead:'Change the follower distribution and the celebrity threshold, and compare write and read load for push, pull and hybrid.',blocks:[
 {t:'lab',fn:'fanout'},
 {t:'teacher',items:['Ask: why not just use a bigger queue for celebrities? Because each post still produces 50 M writes; the queue only delays the problem.']}]},

{title:'Review',tab:'Review',mins:30,out:'Drill + rubric + homework',blocks:[
 {t:'drill',title:'Interviewer push-backs',prefix:'',button:'Draw a question',items:[['"A user unfollows someone. Their posts are still in the feed."','Filter at read time against the follow list; lazily remove from the cached list. A short delay is acceptable.'],['"Users want to see posts from the last 6 months when scrolling."','The cached list holds ~500; beyond that, fall back to the pull path with the cursor.'],['"Likes must update in real time on the post."','Counters in a cache with periodic flush (write-back); approximate counts are fine.'],['"Deleting a post must remove it everywhere."','Mark deleted in the posts DB; feeds skip deleted posts at hydration; async cleanup of lists.'],['"Inactive users get fanned out to for nothing."','Skip fan-out to users inactive for 30 days; build their feed by pulling when they return.']]},
 {t:'flash',items:[['Push model good at…','Fast reads.'],['Push model breaks on…','Celebrities (huge fan-out).'],['Hybrid?','Push for normal users, pull celebrities at read time.'],['Feed cache stores…','postIds, not full posts; hydrate in batch.'],['Photos path?','Pre-signed upload → object storage → CDN.']]},
 {t:'rubric',title:'Score yourself',rows:[['Clarify','Scope, read/write ratio, latency target'],['Data','Posts, follows, feed lists'],['Design','Media path, fan-out choice'],['Challenge','Celebrities, ranking, cache loss'],['Communication','Trade-offs stated with numbers']]},
 {t:'task',title:'Homework',items:['Design Twitter\'s "trending topics" box: what data, how often recomputed, where stored.']}]}
],
labs:{
 fanout(el,api){
  el.innerHTML=`<div class="form"><label>Posts per second: <b data-pv></b><input type="range" min="200" max="5000" step="100" value="1200" data-p></label><label>Average followers: <b data-fv></b><input type="range" min="50" max="1000" step="50" value="200" data-f></label><label>Share of posts by celebrities: <b data-cv></b><input type="range" min="0" max="5" step="0.1" value="1" data-c></label><label>Average celebrity followers (millions): <b data-mv></b><input type="range" min="1" max="100" value="20" data-m></label><label>Feed opens per second: <b data-ov></b><input type="range" min="10000" max="200000" step="5000" value="58000" data-o></label><label>Followees read per feed (pull): <b data-gv></b><input type="range" min="50" max="1000" step="50" value="200" data-g></label></div><div class="tbl"><table><thead><tr><th>Model</th><th>Feed writes/s</th><th>Store reads/s for feeds</th><th>Verdict</th></tr></thead><tbody data-t></tbody></table></div><div class="verdict" data-v></div>`;
  const f=n=>n>=1e9?(n/1e9).toFixed(1)+' B':n>=1e6?(n/1e6).toFixed(1)+' M':n>=1e3?Math.round(n/1e3)+' K':Math.round(n);
  const draw=()=>{const P=+api.$('[data-p]',el).value,F=+api.$('[data-f]',el).value,C=+api.$('[data-c]',el).value/100,M=+api.$('[data-m]',el).value*1e6,O=+api.$('[data-o]',el).value,G=+api.$('[data-g]',el).value;
   ['p','f','c','m','o','g'].forEach(k=>api.$('[data-'+k+'v]',el).textContent=(k==='c'?(C*100).toFixed(1)+'%':k==='m'?M/1e6+' M':(+api.$('[data-'+k+']',el).value).toLocaleString()));
   const pushW=P*(1-C)*F+P*C*M,pushR=O*1,pullW=0,pullR=O*G,hybW=P*(1-C)*F,hybR=O*(1+5);
   api.$('[data-t]',el).innerHTML=[['Push (fan-out on write)',pushW,pushR,pushW>2e6?'<span class="tag red">write storm</span>':'<span class="tag green">ok</span>'],['Pull (fan-out on read)',pullW,pullR,pullR>2e6?'<span class="tag red">read storm</span>':'<span class="tag green">ok</span>'],['Hybrid (pull ~5 celebrities)',hybW,hybR,'<span class="tag green">balanced</span>']].map(r=>`<tr><td>${r[0]}</td><td class="mono">${f(r[1])}</td><td class="mono">${f(r[2])}</td><td>${r[3]}</td></tr>`).join('');
   api.$('[data-v]',el).innerHTML=`Celebrities write only ${(C*100).toFixed(1)}% of posts but cause <b>${Math.round(P*C*M/Math.max(1,pushW)*100)}%</b> of push writes. The hybrid removes them from fan-out and pays a small extra read per feed open instead.`};
  el.addEventListener('input',draw);draw()}
}});
