COURSE.add({id:'s20',n:20,part:'D',track:'Both',
title:'Capstone: full HLD and LLD mock interviews',
goal:'Run one full HLD mock and one full LLD mock under real timing, score both with the rubric, and leave with a personal plan.',
outcomes:['Complete a 40-minute HLD interview with changing requirements','Complete a 35-minute LLD interview with working code','Score yourself honestly and pick three habits to fix','Tell your project story with trade-offs in 2 minutes'],
concept:'interview',
tasks:[{t:'Run the full HLD mock under time and score it.'},{t:'Run the full LLD mock under time and score it.'},{t:'Answer the final interview checkpoint.',auto:'s20cp'},{t:'Review everything due on the Revision page.'},{t:'Rate yourself on the whole course.',auto:'s20sum'}],
modules:[
{title:'How the capstone runs',tab:'Setup',mins:10,out:'Pairs and prompts chosen',lead:'Work in pairs. One person is the candidate for the HLD mock and the interviewer for the LLD mock; the other swaps. The interviewer reads change cards at the right minute and scores with the rubric.',blocks:[
 {t:'table',head:['Interviewer does','Interviewer does not'],rows:[['Give the prompt and answer clarifying questions with the assumptions listed','Volunteer the design'],['Read change cards at the minute shown','Read cards early'],['Ask "why?" and "what does it cost?"','Accept tool names without reasons'],['Score with the rubric right after','Score from memory a day later']]},
 {t:'cards',title:'The two loops, one last time',items:[
  {tag:'HLD',title:'Clarify → interactions → data → simple design → challenge',body:'<p>Say numbers. Start simple. Every part added must answer a requirement or a failure.</p>'},
  {tag:'LLD',title:'Requirements → entities → class diagram → patterns → code → extend',body:'<p>Each rule lives in one class. Patterns only for a reason. Code runs. Extensions add classes, not edits everywhere.</p>'}]}]},

{title:'HLD mock interview (40 minutes)',tab:'HLD mock',mins:45,out:'HLD design + score',lead:'The interviewer picks one prompt. The candidate does not see the hints until the end.',blocks:[
 {t:'cards',title:'Pick a prompt (interviewer)',items:[
  {tag:'Prompt A',title:'Design YouTube',sub:'upload, transcode, watch',body:'<p><b>Assumptions to give if asked:</b> 100 M daily viewers, 500 K uploads/day, average video 300 MB, global users, watch must start within 2 s.</p><p><b>Look for:</b> object storage + CDN, async transcoding pipeline, metadata DB, view counts async, adaptive bitrate.</p>'},
  {tag:'Prompt B',title:'Design Google Docs',sub:'real-time collaborative editing',body:'<p><b>Assumptions:</b> 50 M docs, up to 50 editors per doc, edits visible to others within 200 ms, full history.</p><p><b>Look for:</b> WebSockets, per-document session server, operational transform or CRDTs, operation log + snapshots, presence/cursors.</p>'},
  {tag:'Prompt C',title:'Design food delivery',sub:'order, restaurant, rider',body:'<p><b>Assumptions:</b> 2 M orders/day, 200 cities, rider location every 5 s, peak 3x at dinner.</p><p><b>Look for:</b> order state machine, idempotent payments, geo index for riders, async notifications, matching without double assignment.</p>'}]},
 {t:'timer',total:2400,phases:[[0,420,'Clarify: users, features, scale, never-happen rules'],[420,720,'Interactions: APIs'],[720,1080,'Data: entities, hot reads, risky writes'],[1080,1620,'Simple design + trace one request'],[1620,1920,'Change card A'],[1920,2220,'Change card B'],[2220,2400,'Wrap up: what to build first, top risks']],
  cards:[{at:1620,label:'Change card A · minute 27',title:'"Traffic is 10x what you assumed, and it is concentrated in one region during evening hours."',body:'Expect: where it breaks first, caching/CDN, scaling stateless tiers, queueing, regional capacity, numbers.'},{at:1920,label:'Change card B · minute 32',title:'"A key dependency (storage / payment / transcoding) fails for 15 minutes."',body:'Expect: what users see, timeouts, retries with backoff, degraded mode, queues absorbing work, idempotency on recovery.'}]},
 {t:'rubric',title:'HLD rubric (interviewer scores)',rows:[['Clarify','Users, scale, never-happen rule, scope written down'],['Interactions','Clear APIs with inputs and outputs'],['Data','Entities, main read, riskiest write, storage choice with reason'],['Simple design','Started minimal; traced a request end to end'],['Challenge','Found own weak spots; each fix had a cost'],['Changing requirements','Adapted the design, explained what changed'],['Communication','Thought aloud, numbers, no unexplained buzzwords']]}]},

{title:'LLD mock interview (35 minutes)',tab:'LLD mock',mins:40,out:'Classes + code + score',lead:'Swap roles. The new interviewer picks one prompt.',blocks:[
 {t:'cards',title:'Pick a prompt (interviewer)',items:[
  {tag:'Prompt A',title:'Splitwise',sub:'split expenses in groups',body:'<p><b>Assumptions:</b> users, groups, expenses split equally, by exact amounts or by percentage; show who owes whom; settle up.</p><p><b>Look for:</b> SplitStrategy (Strategy), Expense validation (sum must match), balance sheet map, simplifying debts as an extension.</p>'},
  {tag:'Prompt B',title:'Movie ticket booking (BookMyShow)',sub:'shows, seats, bookings',body:'<p><b>Assumptions:</b> cities, cinemas, screens, shows, seat types with prices, hold seats for 10 minutes during payment.</p><p><b>Look for:</b> Show–Seat relationship, seat hold with expiry, thread-safe booking (lock or conditional update), pricing strategy.</p>'},
  {tag:'Prompt C',title:'Snakes and ladders',sub:'game engine',body:'<p><b>Assumptions:</b> 100-cell board, N players, one die, snakes and ladders configurable, first to 100 wins (exact roll needed).</p><p><b>Look for:</b> Board, Player, Dice (injectable for tests), Game loop, jumps map, rule for exact finish as a strategy.</p>'}]},
 {t:'timer',total:2100,phases:[[0,300,'Requirements and assumptions'],[300,540,'Entities and responsibilities'],[540,900,'Class diagram + patterns'],[900,1680,'Code the core classes and key methods'],[1680,1920,'Change card'],[1920,2100,'Tests you would write; wrap up']],
  cards:[{at:1680,label:'Change card · minute 28',title:'"Add a new rule without rewriting your core class."',body:'Splitwise: split by shares (2:1:1). Tickets: weekday/weekend pricing and a convenience fee. Snakes and ladders: two dice and "roll a 6 to start". Expect: one new class plugged in via a strategy or a decorator.'}]},
 {t:'rubric',title:'LLD rubric (interviewer scores)',rows:[['Requirements','Asked about rules, edge cases, scope'],['Entities','Right classes, one responsibility each'],['Relationships','Correct is-a / has-a / uses'],['Patterns','Used for a stated reason, not decoration'],['Code','Readable, runs, handles edge cases'],['Extension','New rule added as a new class'],['Communication','Explained choices while coding']]}]},

{title:'Final review and your plan',tab:'Final review',mins:25,out:'Personal plan',blocks:[
 {t:'flash',title:'Whole-course flashcards',items:[['First move in any design?','Clarify: users, core actions, scale, never-happen rule.'],['1 M/day ≈ ?','~12 per second.'],['Read-heavy fix order?','Cache → replicas → shard.'],['Hot key fix?','Cache/replicate the key; sharding does not help.'],['Exactly once?','At-least-once + idempotency.'],['Saga vs 2PC?','Saga: local steps + compensations; 2PC: global lock, blocking.'],['Fan-out for celebrities?','Hybrid: pull them at read time.'],['Chat routing?','Connection registry: user → gateway.'],['Geo search?','Cell + neighbours (geohash/quadtree).'],['SOLID in one line each?','One reason to change; extend not edit; safe substitution; small interfaces; depend on abstractions.'],['Strategy vs State?','Client picks strategy; state changes itself.'],['LRU O(1)?','Hash map + doubly linked list.']]},
 {t:'lab',fn:'story',title:'Your project story, final version',intro:'Rewrite it with what you know now: name one alternative and its cost using course vocabulary.'},
 {t:'checklist',title:'Interview-day checklist',items:['My clarifying-question card is ready','I can draw a link shortener and a chat system from memory','I can explain caching, sharding, queues and consistency with one example each','I can code an LRU cache and a parking lot core without notes','I will say "let me start simple" before drawing','I name a technology only after naming the problem it solves','I state the cost of every choice I make']},
 {t:'notes',title:'My 3 habits to fix',label:'From both rubrics, write the three lowest areas and one action each',placeholder:'1. Clarify: I forgot the never-happen rule → write it first on the board\n2. ...\n3. ...',rows:5},
 {t:'teacher',items:['Close by collecting each pair\'s two scores. Share the class\'s weakest area and recommend which session to revisit (for most groups: session 6 consistency, or session 14 SOLID).','Suggest a follow-up plan: one HLD and one LLD mock per week using the prompts not chosen today.']},
 {t:'checkpoint',id:'s20cp',title:'Final interview checkpoint',prompt:'"Design YouTube: users upload videos and watch them. 100 M daily users, global." You have 40 minutes. Where do you start, and what do you draw first?',
  model:'Clarify (upload + watch; live out of scope?) → estimate (views, uploads, storage per day, egress bandwidth) → API (upload URL, video metadata, stream manifest) → data (video metadata in a DB; bytes in object storage) → basic design: upload → object storage → queue → transcoding workers → renditions → CDN; watch: API for metadata + CDN for segments → bottlenecks: egress (CDN), transcoding (workers on a queue), metadata reads (cache) → failures: transcoding retries + DLQ, region outage, CDN origin shielding → trade-offs: cost of storage per rendition, cold vs hot content.',
  followups:[['"Transcoding a 2-hour video takes too long."','Split into chunks and transcode in parallel on many workers; publish when the first renditions are ready.'],['"View counts?"','Async events, batched counters; approximate is fine.'],['"Popular videos in one country."','CDN pre-warming and origin shielding; regional caches.']]},
 {t:'recall',title:'Final recall',items:[['The four questions behind every architecture change?','What problem do we have? Why does the current design fail? What component could solve it? What new problems does it introduce?'],['Measure → ?','Identify the bottleneck → change one thing → measure again.'],['Which component fixes a hot key?','A cache (with key replication or a local copy), not sharding.'],['When is sharding justified?','When writes or data size exceed one primary after caching and replicas.'],['What do you say first in any design round?','Clarifying questions: users, scale, must-haves and the never-happen rule.']]},
 {t:'summary',id:'s20sum',title:'Course summary',learned:['<b>Why each building block exists:</b> load balancers, caches, replicas, queues, shards, CDNs','<b>When to add one:</b> a measured bottleneck or a requirement forces it','<b>When not to:</b> because "big systems use it"','<b>Major trade-offs:</b> consistency vs availability, latency vs cost, simplicity vs scale','<b>Interview skills:</b> clarify, estimate, design simply, find bottlenecks, defend trade-offs'],explain:'Design any system from the course in 30 minutes, justifying every component with a problem it solves.'}]}
]});
