/* Interactive case studies, part B: search autocomplete, web crawler, payment system. */
COURSE.addCase({id:'case-autocomplete',kind:'case',level:'i',concept:'caching',
title:'Search autocomplete',goal:'Suggest the top completions for every keystroke within 100 ms for 100 M users.',
outcomes:['Choose a trie / prefix index and precompute top-k','Serve from memory and cache popular prefixes','Update suggestions offline from query logs','Reason about freshness vs cost'],
tasks:[{t:'Estimate keystroke queries per second.',auto:'cac-cap'},{t:'Predict where the latency budget goes.',auto:'cac-pred'},{t:'Design it yourself, then compare.',auto:'cac-build'},{t:'Answer the interview checkpoint.',auto:'cac-cp'}],
modules:[
{title:'Requirements and estimation',tab:'Estimate',mins:10,blocks:[
 {t:'grid',cols:2,title:'Requirements',items:[{tag:'Functional',title:'What it does',body:'Return the top 5 completions for a typed prefix, ranked by popularity.'},{tag:'Non-functional',tc:'amber',title:'How well',body:'< 100 ms per keystroke; 100 M DAU; suggestions can lag real trends by minutes or hours.'}]},
 {t:'capacity',id:'cac-cap',title:'Estimation · Keystrokes',intro:'Each search has ~6 keystrokes; each keystroke is a request. Assume 10 searches per user per day.',scenarios:[{name:'Autocomplete',dau:100e6,rpu:60,ratio:10000,obj:200,peak:3}],ask:['reqDay','qps','peak']}]},
{title:'Design',tab:'Design',mins:20,blocks:[
 {t:'predict',id:'cac-pred',title:'What happens next?',scenario:'First version: on each keystroke, run <code>SELECT query FROM searches WHERE query LIKE \'pre%\' GROUP BY query ORDER BY count DESC LIMIT 5</code> on the search-log database.',metrics:[['Requests / s','~200 K peak','bad'],['Query time','1.8 s','bad'],['Budget','100 ms','']],q:'What would you change?',opts:[['Precompute top-5 per prefix in an in-memory trie, rebuilt offline from logs',1,'Answering becomes a memory lookup. Aggregation moves to a batch job that runs every few minutes or hours.'],['Add an index on query',0,'Faster prefix match, but grouping and sorting billions of log rows per keystroke is still far too slow.'],['Add read replicas',0,'Each replica runs the same slow query.']],takeaway:'Move expensive computation off the request path; serve precomputed answers from memory.'},
 {t:'builder',id:'cac-build',title:'Design it yourself · Autocomplete',reqs:['Top-5 completions per keystroke','< 100 ms','~200 K requests/s at peak','Suggestions refresh from query logs','Personalisation optional'],palette:['client','cdn','lb','api','cache','db:Log store','kafka','worker','search'],
  ref:{nodes:['client@0,1','cdn@1,0:CDN / browser cache|popular prefixes','lb@1,1','api@2,1:Suggest servers|in-memory trie','cache@3,0:Redis|prefix → top 5','kafka@2,2:Query log stream','worker@3,2:Batch aggregator','db@4,2:Log store'],edges:['client>cdn','client>lb','lb>api','api>cache','kafka>worker','worker>db','worker>api:new trie snapshot'],
   need:{api:'Serves lookups from an in-memory trie holding precomputed top-k per prefix.',kafka:'Collects searches for offline aggregation.',worker:'Aggregates counts and builds new trie snapshots.',lb:'Spreads lookups.'},
   optional:{cache:'Hot prefixes; or the trie servers are the cache.',cdn:'Short-TTL caching of very common prefixes, plus browser caching.',db:'Long-term log storage.',search:'An existing search engine with completion suggesters can replace a custom trie.'},whyNot:{},tradeoffs:'Freshness vs cost: rebuilding hourly is cheap; trending topics need a faster streaming layer. Debounce keystrokes on the client to cut traffic.'}}]},
{title:'Follow-ups',tab:'Follow-ups',mins:10,blocks:[
 {t:'checkpoint',id:'cac-cp',title:'Interview checkpoint',prompt:'"Design typeahead suggestions for a search box with 100 M daily users."',model:'Client debounces (~100 ms) and caches. Suggest servers hold a trie with top-5 per node, sharded by prefix range, replicated. Query logs → stream → batch aggregation → new trie snapshot → atomic swap. Filter offensive terms at build time.',followups:[['"Trending news must appear within minutes."','A small streaming layer counts recent queries and merges with the batch trie at read time.'],['"Shard the trie how?"','By first characters, with hot prefixes split further; replicate each shard.']]},
 {t:'recall',title:'Active recall',items:[['Why precompute top-k per prefix?','So a keystroke is a memory lookup, not an aggregation query.'],['How do suggestions update?','Logs are aggregated offline and a new trie snapshot replaces the old one.'],['One client-side optimisation?','Debounce keystrokes and cache recent prefixes.']]}]}
]});

COURSE.addCase({id:'case-crawler',kind:'case',level:'x',concept:'queues',
title:'Web crawler',goal:'Crawl 1 billion pages a month politely, without fetching the same page twice.',
outcomes:['Design the URL frontier with per-host politeness','Deduplicate URLs and content','Scale fetchers with queues','Handle traps and failures'],
tasks:[{t:'Estimate pages per second and storage.',auto:'ccr-cap'},{t:'Design it yourself, then compare.',auto:'ccr-build'},{t:'Fix the politeness problem (prediction).',auto:'ccr-pol'},{t:'Answer the interview checkpoint.',auto:'ccr-cp'}],
modules:[
{title:'Requirements and estimation',tab:'Estimate',mins:10,blocks:[
 {t:'grid',cols:2,title:'Requirements',items:[{tag:'Functional',title:'What it does',body:'Start from seed URLs, fetch pages, extract links, store content for indexing, recrawl periodically.'},{tag:'Non-functional',tc:'amber',title:'How well',body:'1 B pages/month; obey robots.txt; at most ~1 request/s per host; skip duplicates and traps.'}]},
 {t:'capacity',id:'ccr-cap',title:'Estimation · Pages per second',intro:'Model one "user" doing all the work: 1 B pages per 30 days ≈ 33 M a day, 500 KB per page.',scenarios:[{name:'Crawler',dau:1,rpu:33e6,ratio:0.0001,obj:500e3,peak:1.5}],ask:['reqDay','qps','storageDay','storageYear']}]},
{title:'Design',tab:'Design',mins:20,blocks:[
 {t:'predict',id:'ccr-pol',title:'What happens next?',scenario:'Your 500 fetchers pull URLs from one shared FIFO queue. A popular site has 2 million URLs queued in a row. Its owner emails you: your crawler is sending 400 requests per second and taking their site down.',q:'What do you change?',opts:[['Per-host queues; each host is served by one fetcher at a limited rate',1,'The frontier maps each host to one queue; a fetcher takes the next host whose delay has passed. Politeness is built into the structure.'],['Fewer fetchers',0,'Slows the whole crawl and still bursts one host.'],['Random order',0,'Reduces bursts by luck, not by design.']],takeaway:'The frontier is two-level: priority decides what to crawl; per-host queues decide when.'},
 {t:'builder',id:'ccr-build',title:'Design it yourself · Web crawler',reqs:['1 B pages/month','Politeness: robots.txt and per-host rate','No duplicate fetches','Store raw pages for indexing','Recrawl changed pages'],palette:['queue','worker','db:URL store','cache','obj','kafka','dns','search'],
  ref:{nodes:['queue@0,1:URL frontier|priority + per-host queues','worker@1,1:Fetchers','dns@1,0:DNS cache','obj@2,0:Page store|raw HTML','kafka@2,1:Fetched-page stream','search@3,1:Parser + link extractor','cache@3,0:Seen-URL filter|Bloom filter','db@3,2:URL store|status, last crawl'],edges:['queue>worker','worker>dns','worker>obj','worker>kafka','kafka>search','search>cache:new links','cache>queue:unseen only','search>db'],
   need:{queue:'The frontier: prioritised, with per-host politeness.',worker:'Fetch pages concurrently.',obj:'Raw pages for indexing.',cache:'Fast "have we seen this URL?" checks (Bloom filter).',db:'URL metadata: status, last crawl, content hash.',search:'Parse pages and extract links (here standing in for the parser workers).'},
   optional:{dns:'Cached DNS lookups: DNS becomes a bottleneck at this rate.',kafka:'Decouples fetchers from parsers.'},whyNot:{},tradeoffs:'Bloom filters save memory but have false positives (a few URLs skipped). Content hashing finds duplicate pages under different URLs. Trap detection: limit depth and URLs per host.'}}]},
{title:'Follow-ups',tab:'Follow-ups',mins:10,blocks:[
 {t:'checkpoint',id:'ccr-cp',title:'Interview checkpoint',prompt:'"Design a web crawler for a search engine."',model:'Seeds → frontier (priority queues → per-host queues with delays) → fetchers (robots cache, DNS cache) → page store + stream → parsers extract links → URL normalisation → seen filter → frontier. Content hashes dedupe pages; recrawl by change rate.',followups:[['"A calendar site generates infinite URLs."','Crawler trap: cap depth and pages per host, detect repeating patterns.'],['"How do you scale the frontier?"','Partition hosts across frontier nodes by hash(host) so one node owns a host’s politeness.']]},
 {t:'recall',title:'Active recall',items:[['How is politeness enforced?','Per-host queues with a minimum delay, served by one fetcher at a time; obey robots.txt.'],['How do you avoid refetching URLs?','Normalise URLs and check a seen-set (Bloom filter + URL store).'],['What is a crawler trap?','A site generating endless URLs; limit depth and pages per host.']]}]}
]});

COURSE.addCase({id:'case-payments',kind:'case',level:'x',concept:'consistency',
title:'Payment system',goal:'Accept payments for an e-commerce site: charge exactly once, keep a correct ledger, and reconcile with providers.',
outcomes:['Use idempotency end to end','Model money with a double-entry ledger','Handle provider timeouts with pending states and reconciliation','Choose strong consistency where money moves'],
tasks:[{t:'Decide what happens after a provider timeout.',auto:'cpy-pred'},{t:'Design it yourself, then compare.',auto:'cpy-build'},{t:'Explain double-entry bookkeeping with the diagram.'},{t:'Answer the interview checkpoint.',auto:'cpy-cp'}],
modules:[
{title:'Requirements and the hard part',tab:'Requirements',mins:10,blocks:[
 {t:'grid',cols:2,title:'Requirements',items:[{tag:'Functional',title:'What it does',body:'Charge a customer, pay out merchants, refunds, payment status.'},{tag:'Never-happen rule',tc:'red',title:'Money is created or lost',body:'A customer is charged twice, or a charge is recorded without the money, or vice versa.'}]},
 {t:'predict',id:'cpy-pred',title:'What happens next?',scenario:'Your service calls the card provider to charge ₹2,000. After 10 s the call <b>times out</b>. You do not know whether the charge happened.',q:'What should the system do?',opts:[['Keep the payment "pending" and retry with the same idempotency key; reconcile later',1,'The provider returns the original result for the same key, so a retry cannot charge twice. A reconciliation job resolves anything still pending using the provider’s records.'],['Mark it failed and ask the user to pay again',0,'If the first charge succeeded, the user is charged twice.'],['Mark it successful',0,'If it failed, you ship goods without being paid.'],['Retry with a new request',0,'Could create a second charge.']],takeaway:'A timeout is "unknown", not "failed". Model unknown explicitly.'}]},
{title:'Design it yourself',tab:'Design',mins:20,blocks:[
 {t:'builder',id:'cpy-build',title:'Design it yourself · Payment system',reqs:['Charge customers through external providers','Exactly-once effect despite retries','Correct ledger of all money movements','Daily reconciliation with providers','Refunds and merchant payouts'],palette:['client','lb','api','db:PostgreSQL','cache','queue','kafka','worker','provider:Payment provider'],
  ref:{nodes:['client@0,1:Checkout','lb@1,1','api@2,1:Payment service','db@3,1:PostgreSQL|payments + ledger','provider@3,0:Payment provider','queue@2,2:Queue','worker@3,2:Reconciliation + payouts'],edges:['client>lb','lb>api:Idempotency-Key','api>db','api>provider:same key on retry','provider~>api:webhook','api>queue','queue>worker','worker>db','worker>provider:settlement reports'],
   need:{api:'Orchestrates the payment state machine: created → pending → succeeded/failed.',db:'ACID transactions for payment state and a double-entry ledger.',provider:'Moves the money.',worker:'Reconciles pending payments and settlement files; runs payouts.',lb:'Spreads traffic.'},
   optional:{queue:'Feeds background jobs.',kafka:'Event stream for analytics, fraud and notifications.'},whyNot:{cache:'Payment state must come from the source of truth; caching balances risks wrong decisions.'},tradeoffs:'Strong consistency over availability for money. Synchronous provider calls vs async confirmation via webhooks: handle both, idempotently.'}}]},
{title:'Ledger and follow-ups',tab:'Ledger',mins:15,blocks:[
 {t:'diagram',title:'Diagram · Double-entry ledger for one purchase',nodes:['cust@0,0:Customer card|−₹2,000','clearing@1,0:Provider clearing|+₹2,000 / −₹2,000','merchant@2,0:Merchant balance|+₹1,960','fees@2,1:Our fee revenue|+₹40'],edges:['cust>clearing:charge','clearing>merchant','clearing>fees'],caption:'Every movement is recorded as entries that sum to zero. If the books do not balance, there is a bug, and you can find it. Entries are append-only; corrections are new entries, never edits.'},
 {t:'checkpoint',id:'cpy-cp',title:'Interview checkpoint',prompt:'"Design a payment system that never charges a customer twice."',model:'Client sends an idempotency key; the service stores it with the payment row (unique constraint) and reuses it with the provider. Payment is a state machine; provider timeouts leave it pending; webhooks and retries move it forward idempotently; a reconciliation job compares with provider reports daily. Ledger is double-entry and append-only.',followups:[['"The webhook arrives before your own call returns."','Both paths update the same payment row with a conditional state transition; whichever is first wins, the other is a no-op.'],['"How do you scale?"','Partition payments by merchant or payment id; the ledger can be sharded by account with careful cross-shard transfers (sagas).']]},
 {t:'recall',title:'Active recall',items:[['What does an idempotency key guarantee?','Repeating the same request produces one effect and returns the original result.'],['Why double-entry?','Every movement balances to zero, so errors are detectable and the history is auditable.'],['What does reconciliation do?','Compares your records with the provider’s to resolve pending or mismatched payments.'],['Why treat a timeout as pending?','The outcome is unknown; guessing either way can lose money.']]}]}
]});
