/* Interactive case studies, part A: YouTube, notification service, Google Drive / Dropbox, ticket booking.
   Each follows: requirements → estimation → API + data → design it yourself → scale and break → trade-offs and follow-ups. */
COURSE.addCase({id:'case-youtube',kind:'case',level:'x',concept:'interview',
title:'YouTube',goal:'Design video upload and playback for 100 M daily users worldwide.',
outcomes:['Separate video bytes from metadata','Explain the transcoding pipeline with a queue','Justify a CDN with bandwidth numbers','Handle failures in a long-running pipeline'],
tasks:[{t:'Estimate uploads, storage per day and egress bandwidth.',auto:'cyt-cap'},{t:'Design it yourself, then compare.',auto:'cyt-build'},{t:'Reveal the pipeline stage by stage, predicting each step.',auto:'cyt-evo'},{t:'Answer the interview checkpoint.',auto:'cyt-cp'}],
modules:[
{title:'Requirements and estimation',tab:'Estimate',mins:15,blocks:[
 {t:'grid',cols:2,title:'Requirements',items:[{tag:'Functional',title:'What it does',body:'<ul class="clean"><li>Upload a video</li><li>Watch a video, adaptive quality</li><li>Search and view counts (light)</li></ul>'},{tag:'Non-functional',tc:'amber',title:'How well',body:'<ul class="clean"><li>100 M DAU, global</li><li>Playback starts in < 2 s</li><li>Uploaded videos are never lost</li><li>Views ≫ uploads (≈ 200:1)</li></ul>'}]},
 {t:'capacity',id:'cyt-cap',title:'Estimation · Views, uploads, storage, bandwidth',intro:'Treat each "request" as a video view and each write as an upload. The object size is the average bytes streamed per view (~50 MB) to estimate egress.',scenarios:[{name:'Video platform',dau:100e6,rpu:5,ratio:200,obj:50e6,peak:3}],ask:['reqDay','qps','peak','writesDay','storageDay','bandwidth']},
 {t:'reveal',title:'So what do the numbers say?',items:[{q:'Average egress ≈ 1.4 TB/s. What does that force?',a:'No app server can stream that: video must come from a CDN, with your origin serving only cache misses.'},{q:'~2.5 M uploads/day × several renditions. Where do bytes live?',a:'Object storage (cheap, durable, effectively unlimited); the database holds only metadata.'}]}]},
{title:'API and data model',tab:'API + data',mins:10,blocks:[
 {t:'table',title:'API',head:['Call','Purpose'],rows:[['<code>POST /videos</code> → {videoId, uploadUrl}','Create metadata, return a signed upload URL'],['<code>PUT {uploadUrl}</code>','Client uploads bytes straight to object storage'],['<code>GET /videos/{id}</code>','Title, status, renditions, manifest URL'],['<code>GET {cdn}/v/{id}/master.m3u8</code>','Adaptive streaming manifest; segments via CDN']]},
 {t:'hints',title:'Think it through · Data model',q:'What tables or entities do you need, and what is the hot read?',write:true,hints:['Separate the video record from its files.','Which read happens on every play?'],solution:'<b>Video</b>(id, owner, title, status: uploading/processing/ready, created) · <b>Rendition</b>(videoId, resolution, codec, storage key) · <b>ViewCount</b> (approximate, async). Hot read: video metadata by id → cached; bytes come from the CDN.'}]},
{title:'Design it yourself',tab:'Design',mins:20,blocks:[
 {t:'builder',id:'cyt-build',title:'Design it yourself · YouTube',reqs:['Upload and watch videos','100 M DAU, global','Playback starts in < 2 s','Transcode to several qualities','Never lose an uploaded video'],palette:['client','lb','api','db:PostgreSQL','cache','obj','cdn','queue','worker','kafka','search','shard'],
  ref:{nodes:['client@0,1','cdn@1,0:CDN|video segments','lb@1,1','api@2,1:API servers','cache@3,0:Redis|metadata','db@3,1:PostgreSQL|video metadata','obj@4,0:Object storage|raw + renditions','queue@2,2:Transcode queue','worker@3,2:Transcoding workers'],edges:['client>cdn','client>lb','lb>api','api>cache','api>db','api>queue','queue>worker','worker>obj','cdn~>obj:origin','client~>obj:direct upload'],
   need:{cdn:'1+ TB/s of egress must be served near viewers.',obj:'Raw uploads and renditions: huge, durable, cheap.',queue:'Transcoding takes minutes; uploads must not wait.',worker:'Transcode in parallel; scale on queue depth.',api:'Metadata, upload URLs, status.',db:'Video metadata and status.',lb:'Spread API traffic.'},
   optional:{cache:'Hot metadata for popular videos.',search:'Search by title/tags if in scope.',kafka:'An event log if many systems consume upload/view events.',shard:'Metadata sharding at very large scale.'},whyNot:{},
   tradeoffs:'Storage cost grows with renditions per video: drop rare renditions for old videos. Chunked parallel transcoding vs simplicity. Popular videos stay hot at the edge; the long tail hits the origin.'}}]},
{title:'Scale and break it',tab:'Scale + break',mins:15,blocks:[
 {t:'evolve',id:'cyt-evo',title:'Diagram · Building the pipeline one problem at a time',stages:[
  {label:'Naive',nodes:['client@0,1','api@1,1:App server','db@2,1:Database|stores video bytes'],edges:['client>api:upload + stream','api>db'],problem:'Videos are uploaded to and streamed from the app server; bytes sit in the database.',fix:'The simplest thing that works for a demo.'},
  {label:'Object storage',nodes:['client@0,1','api@1,1:API servers','db@2,1:Database|metadata','obj@2,0:Object storage'],edges:['client>api','api>db','client>obj:signed upload'],predict:{q:'The database is 40 TB and growing 300 TB/year; backups take days. What changes?',opts:[['Move bytes to object storage; keep metadata in the DB',1,'Databases are for small, structured records; blobs belong in object storage.'],['Shard the database',0,'Sharding blobs is expensive and pointless.']]},problem:'Bytes overwhelm the database.',fix:'Object storage for bytes; direct signed uploads.',introduces:'Two stores to keep consistent (metadata says "ready" only after the file exists).'},
  {label:'Transcode queue',nodes:['client@0,1','api@1,1:API servers','db@2,1:Database|metadata','obj@2,0:Object storage','queue@1,2:Queue','worker@2,2:Transcoders'],edges:['client>api','api>db','client>obj','api>queue','queue>worker','worker>obj'],predict:{q:'Phones cannot play the raw 4K upload, and transcoding takes 10 minutes. Next?',opts:[['A queue of transcode jobs processed by workers',1,'Long CPU work leaves the request path and scales independently.'],['Transcode inside the upload request',0,'The request would hang for 10 minutes.']]},problem:'Every device needs several qualities; transcoding is slow.',fix:'Queue + workers produce renditions; status moves processing → ready.',introduces:'Retries, poison jobs (DLQ), progress tracking.'},
  {label:'CDN',nodes:['client@0,1','cdn@1,0:CDN','api@1,1:API servers','db@2,1:Database|metadata','obj@2,0:Object storage','queue@1,2:Queue','worker@2,2:Transcoders'],edges:['client>cdn:segments','client>api','api>db','cdn~>obj:origin','api>queue','queue>worker','worker>obj'],predict:{q:'Egress is 1.4 TB/s and far viewers buffer. Next?',opts:[['Serve segments from a CDN',1,'Edges near viewers cut latency and absorb the bandwidth.'],['Bigger object storage',0,'Distance and bandwidth are the problem, not capacity.']]},problem:'Bandwidth and distance.',fix:'CDN in front of object storage; adaptive bitrate streaming.',introduces:'CDN cost; cold long-tail videos still hit the origin.'}]},
 {t:'predict',kind:'debug',title:'Debugging scenario · Uploads stuck in "processing"',scenario:'Users report videos stuck in "processing" for hours.',metrics:[['Transcode queue depth','180 K','bad'],['Oldest job','3 h','bad'],['Worker CPU','95%','warn'],['Jobs failing repeatedly','2% of jobs','warn']],q:'What would you look at first?',opts:[['Worker capacity vs arrival rate, and poison jobs retrying forever',1,'Workers are saturated and failing jobs are retried endlessly, consuming capacity. Autoscale on queue age and send repeat failures to a DLQ.'],['The CDN',0,'The CDN serves finished videos; these never finished.'],['The database',0,'No database symptoms are shown.']],takeaway:'For pipelines, alert on queue age and isolate poison messages.'}]},
{title:'Trade-offs and follow-ups',tab:'Follow-ups',mins:15,blocks:[
 {t:'checkpoint',id:'cyt-cp',title:'Interview checkpoint',prompt:'"Walk me through what happens from the moment a creator presses Upload until a viewer in another country presses Play."',model:'Create metadata → signed URL → direct upload to object storage → completion event → transcode queue → workers create renditions (chunked, parallel) → manifest → status ready → viewer gets metadata from API (cached) and segments from the nearest CDN edge, which pulls from origin once.',followups:[['"A 3-hour video takes forever to transcode."','Split into segments and transcode in parallel; publish lower qualities first.'],['"How do you count views?"','Async events, batched aggregation, eventually consistent counts.'],['"Copyright checks?"','Another consumer of the upload event; block publishing until it passes.']]},
 {t:'recall',title:'Active recall',items:[['Where do video bytes live?','Object storage, served through a CDN.'],['Why a transcode queue?','Transcoding takes minutes; uploads should return at once and work scales independently.'],['What forces a CDN?','Terabytes per second of egress and far-away viewers.'],['What is adaptive bitrate streaming?','Video split into segments at several qualities; the player switches quality as bandwidth changes.']]}]}
]});

COURSE.addCase({id:'case-notify',kind:'case',level:'i',concept:'queues',
title:'Notification service',goal:'Send email, SMS and push to 50 M users reliably, including bulk campaigns, without delaying urgent messages.',
outcomes:['Decouple the API from delivery with queues','Prioritise urgent traffic over bulk','Handle provider failures with retries, DLQ and fallback','Map the HLD to classes (LLD bridge)'],
tasks:[{t:'Estimate peak sends per second for a campaign.',auto:'cnt-cap'},{t:'Design it yourself, then compare.',auto:'cnt-build'},{t:'Run the queue lab for a 10 M-user blast.',auto:'cnt-q'},{t:'Answer the interview checkpoint.',auto:'cnt-cp'}],
modules:[
{title:'Requirements and estimation',tab:'Estimate',mins:10,blocks:[
 {t:'grid',cols:2,title:'Requirements',items:[{tag:'Functional',title:'What it does',body:'<ul class="clean"><li>Send via email, SMS, push</li><li>Templates, user preferences, opt-out</li><li>Delivery status</li></ul>'},{tag:'Non-functional',tc:'amber',title:'How well',body:'<ul class="clean"><li>OTPs within seconds</li><li>Marketing blasts to 10 M users</li><li>No duplicates where possible; never lose an OTP</li></ul>'}]},
 {t:'capacity',id:'cnt-cap',title:'Estimation · Daily volume',scenarios:[{name:'Notifications',dau:50e6,rpu:6,ratio:0.0001,obj:2000,peak:5}],ask:['reqDay','qps','peak']}]},
{title:'Design it yourself',tab:'Design',mins:20,blocks:[
 {t:'builder',id:'cnt-build',title:'Design it yourself · Notification service',reqs:['Email, SMS and push','OTPs must arrive in seconds','10 M-user marketing blasts','Providers sometimes fail or throttle','Respect opt-outs'],palette:['client','lb','api','db:PostgreSQL','cache','queue','kafka','worker','provider:Providers','dlq'],
  ref:{nodes:['client@0,1:Internal services','lb@1,1','api@2,1:Notification API','db@3,1:Preferences + status','cache@3,0:Preference cache','queue@2,2:Priority queues|per channel','worker@3,2:Channel workers','provider@4,2:Providers|SES · Twilio · FCM','dlq@4,1:Dead-letter queue'],edges:['client>lb','lb>api','api>cache','api>db','api>queue','queue>worker','worker>provider','worker>dlq:after N failures','worker>db:status'],
   need:{api:'Validates, applies preferences, enqueues.',queue:'Separate queues per channel and priority so blasts never delay OTPs.',worker:'Call providers within their rate limits; retries with backoff.',provider:'External delivery.',db:'Preferences, templates, delivery status.',dlq:'Messages that keep failing go aside for inspection.'},
   optional:{cache:'Preferences are read for every send.',kafka:'If many consumers need the event stream (analytics).',lb:'Spreads API traffic.'},whyNot:{},tradeoffs:'At-least-once delivery means rare duplicates: dedupe with an idempotency key per notification. Provider fallback improves delivery but can double-send if the first provider was merely slow.'}}]},
{title:'Scale and break it',tab:'Lab',mins:15,blocks:[
 {t:'queuesim',id:'cnt-q',title:'Lab · The blast: queue depth and workers',intro:'Treat each "upload" as a notification job that takes 1 s of provider time. Switch to async, turn on the burst (the blast), and size workers so the queue drains in minutes.',jobSecs:1,rps:60,workers:20,cap:5000},
 {t:'lldmap',title:'HLD → LLD · The worker box',hld:{nodes:['api@0,0:Notification API','queue@1,0:Queue','worker@2,0:Workers','provider@3,0:Providers'],edges:['api>queue','queue>worker','worker>provider']},focus:'Which of these are classes in the worker’s code?',pool:[['Channel (interface)',1,'One implementation per channel.'],['EmailChannel',1,'Formats and sends email via a provider.'],['RetryPolicy',1,'Strategy for backoff and max attempts.'],['ProviderAdapter',1,'Wraps each vendor SDK.'],['RabbitMQ cluster',0,'Infrastructure.'],['Kubernetes pod',0,'Deployment detail.']],mapping:[['Workers','Worker, Channel, EmailChannel/SMSChannel/PushChannel, RetryPolicy, DeadLetterHandler'],['Providers','ProviderAdapter + SesAdapter/TwilioAdapter/FcmAdapter']]}]},
{title:'Trade-offs and follow-ups',tab:'Follow-ups',mins:10,blocks:[
 {t:'checkpoint',id:'cnt-cp',title:'Interview checkpoint',prompt:'"A 10 M-user marketing blast is going out, and at the same time OTP codes are arriving late. Why, and how do you fix it?"',model:'Both share one queue: OTPs wait behind millions of marketing jobs. Separate queues (or strict priorities) per urgency; dedicated workers for OTPs; throttle the blast to provider limits; monitor queue age per priority.',followups:[['"The SMS provider is throttling us."','Respect its rate limit with a token bucket per provider; back off on 429; fail over for OTPs only.'],['"A user unsubscribed mid-blast."','Check preferences at send time (cached), not only at enqueue time.']]},
 {t:'recall',title:'Active recall',items:[['Why separate queues by priority?','So bulk traffic never delays urgent messages like OTPs.'],['How do you avoid duplicate sends on retry?','An idempotency key per notification, checked before calling the provider.'],['What goes to a dead-letter queue?','Messages that keep failing after N attempts.'],['Where does LLD meet HLD here?','The worker box becomes Channel, RetryPolicy and provider adapter classes.']]}]}
]});

COURSE.addCase({id:'case-drive',kind:'case',level:'x',concept:'storage',
title:'Google Drive / Dropbox',goal:'Store, sync and share files across devices for 50 M users.',
outcomes:['Split files into chunks and deduplicate','Sync changes across devices efficiently','Separate metadata (strongly consistent) from blobs','Handle conflicting edits'],
tasks:[{t:'Estimate storage per day and per year.',auto:'cdr-cap'},{t:'Design it yourself, then compare.',auto:'cdr-build'},{t:'Choose how to sync a 2 GB file edit.',auto:'cdr-sync'},{t:'Answer the interview checkpoint.',auto:'cdr-cp'}],
modules:[
{title:'Requirements and estimation',tab:'Estimate',mins:10,blocks:[
 {t:'grid',cols:2,title:'Requirements',items:[{tag:'Functional',title:'What it does',body:'<ul class="clean"><li>Upload, download, delete files</li><li>Sync across a user’s devices</li><li>Share with others; version history</li></ul>'},{tag:'Non-functional',tc:'amber',title:'How well',body:'<ul class="clean"><li>Never lose a file</li><li>Sync within seconds</li><li>Large files (GBs) and weak networks</li></ul>'}]},
 {t:'capacity',id:'cdr-cap',title:'Estimation · Storage growth',scenarios:[{name:'File sync',dau:50e6,rpu:10,ratio:4,obj:2e6,peak:3}],ask:['reqDay','qps','writesDay','storageDay','storageYear']}]},
{title:'Sync design',tab:'Sync',mins:15,blocks:[
 {t:'predict',id:'cdr-sync',title:'What happens next?',scenario:'A user edits one slide in a <b>2 GB</b> presentation on their laptop. Their phone and tablet must get the new version.',q:'How should the change be uploaded and synced?',opts:[['Split files into ~4 MB chunks by content hash; upload and download only changed chunks',1,'One edit changes a few chunks. Hashes also deduplicate identical chunks across users. Devices learn of changes from a metadata change feed.'],['Re-upload the whole 2 GB file',0,'Slow and expensive, and it fails often on weak networks.'],['Email the file to the other devices',0,'Not a sync design.']],takeaway:'Chunking turns big-file sync into small, resumable, deduplicated transfers.'},
 {t:'diagram',title:'Diagram · Upload and sync with chunks',nodes:['client@0,1:Laptop','api@1,1:Metadata service','db@2,1:Metadata DB|files, versions, chunk lists','obj@2,0:Chunk store|by hash','kafka@2,2:Change feed','client2@0,2:Phone'],edges:['client>api:1. which chunks exist?','client>obj:2. upload new chunks','api>db:3. commit new version','db>kafka:4. change event','kafka>client2:5. notify','client2>obj:6. fetch changed chunks'],caption:'Metadata commits are transactional (a version is visible only when all its chunks exist). Chunks are immutable and content-addressed, so they cache and deduplicate well.'}]},
{title:'Design it yourself',tab:'Design',mins:20,blocks:[
 {t:'builder',id:'cdr-build',title:'Design it yourself · Dropbox',reqs:['Upload, download and sync files across devices','Files up to several GB','Share files and folders','Never lose data','Conflicting edits on two offline devices'],palette:['client','lb','api','db:PostgreSQL','cache','obj','cdn','queue','worker','kafka','ws'],
  ref:{nodes:['client@0,1','lb@1,1','api@2,1:Metadata service','db@3,1:Metadata DB|sharded by user','obj@3,0:Chunk store|content hash','kafka@3,2:Change feed','ws@2,2:Notification service|long-poll / WS','cache@4,1:Metadata cache'],edges:['client>lb','lb>api','api>db','client~>obj:chunks','db>kafka','kafka>ws','ws>client','api>cache'],
   need:{api:'Commits versions, checks which chunks exist, permissions.',db:'Files, versions, chunk lists, shares: needs transactions.',obj:'Immutable, deduplicated chunks.',kafka:'Ordered change events per user for sync.',ws:'Tells devices to pull changes.',lb:'Spreads traffic.'},
   optional:{cache:'Hot metadata (folder listings).',cdn:'Popular shared files.',queue:'Background jobs (thumbnails, virus scan).',worker:'Runs those jobs.'},whyNot:{},tradeoffs:'Strong consistency for metadata, eventual for notifications. Conflicts: keep both copies ("conflicted copy") rather than silently losing an edit.'}}]},
{title:'Trade-offs and follow-ups',tab:'Follow-ups',mins:10,blocks:[
 {t:'checkpoint',id:'cdr-cp',title:'Interview checkpoint',prompt:'"Two devices edit the same file while offline, then reconnect. What happens?"',model:'Each edit is based on a version. The first commit wins; the second commit sees its base version is stale (optimistic concurrency) and is saved as a conflicted copy, both visible to the user. Never silently overwrite.',followups:[['"Why not lock files while editing?"','Locks fail offline and when devices disappear; optimistic concurrency fits sync better.'],['"How does dedup save storage?"','Identical chunks (same hash) are stored once and referenced by many files.']]},
 {t:'recall',title:'Active recall',items:[['Why chunk files?','Only changed chunks transfer; uploads resume; identical chunks deduplicate.'],['Why must metadata be strongly consistent?','A version must never point at chunks that do not exist, and permissions must be exact.'],['How do devices learn of changes?','A change feed plus a notification channel (long-poll or WebSocket); they then pull metadata and chunks.'],['How are offline conflicts handled?','Optimistic concurrency; save a conflicted copy instead of losing an edit.']]}]}
]});

COURSE.addCase({id:'case-tickets',kind:'case',level:'x',concept:'consistency',
title:'Ticket booking',goal:'Sell 50,000 concert seats to 2 million people in the first minute without double-booking.',
outcomes:['Protect the never-happen rule with atomic holds','Absorb a flash crowd with a waiting room','Serve the seat map from cache, the purchase from the database','Keep payments idempotent'],
tasks:[{t:'Predict the bottleneck at on-sale time.',auto:'ctk-bn'},{t:'Design it yourself, then compare.',auto:'ctk-build'},{t:'Explain the hold → pay → confirm flow.'},{t:'Answer the interview checkpoint.',auto:'ctk-cp'}],
modules:[
{title:'Requirements and the flash crowd',tab:'Requirements',mins:10,blocks:[
 {t:'grid',cols:2,title:'Requirements',items:[{tag:'Functional',title:'What it does',body:'<ul class="clean"><li>Browse events and seat maps</li><li>Hold seats for 10 minutes</li><li>Pay and receive tickets</li></ul>'},{tag:'Never-happen rule',tc:'red',title:'Two people, one seat',body:'Two buyers must never get the same seat. A paid seat must never be released.'}]},
 {t:'predict',id:'ctk-bn',kind:'bottleneck',title:'Where is the bottleneck?',scenario:'Friday, 10:00:00. A major artist goes on sale.',metrics:[['Users arriving','2 M in 60 s','bad'],['Seats','50,000',''],['Seat-map reads / s','400 K','bad'],['Hold attempts / s','150 K','bad'],['DB CPU','100%','bad']],q:'What do you add first?',opts:[['A virtual waiting room that admits buyers at a controlled rate',1,'Only a few thousand buyers can usefully compete for seats per minute. A queue in front protects everything behind it and is fair.'],['More database replicas',0,'Holds are writes to the primary; replicas do not help, and seat maps can come from cache.'],['A bigger cache only',0,'Caching seat maps helps reads but holds still overwhelm the database.']],takeaway:'When demand vastly exceeds supply, shape the demand (waiting room) instead of scaling for a crowd that cannot all succeed.'}]},
{title:'Design it yourself',tab:'Design',mins:20,blocks:[
 {t:'builder',id:'ctk-build',title:'Design it yourself · Ticket booking',reqs:['2 M users in the first minute for 50 K seats','Seat map visible to everyone','Hold a seat for 10 minutes while paying','Never double-book','Payment provider may time out'],palette:['client','cdn','lb','gw','api','db:PostgreSQL','cache','queue','worker','provider:Payment provider'],
  ref:{nodes:['client@0,1','cdn@1,0:CDN|static + seat-map snapshots','gw@1,1:Waiting room|admits N/s','api@2,1:Booking service','cache@3,0:Redis|seat map, holds','db@3,1:PostgreSQL|seats, orders','queue@2,2:Queue','worker@3,2:Hold expiry + reconciliation','provider@4,1:Payment provider'],edges:['client>cdn','client>gw','gw>api','api>cache','api>db:conditional hold','api>provider:idempotency key','api>queue','queue>worker','worker>db'],
   need:{gw:'Waiting room: admits buyers at the rate the system can serve.',api:'Holds, orders, payment orchestration.',db:'The source of truth for seat status; conditional updates prevent double booking.',cache:'Seat-map reads for millions of browsers.',provider:'Charges the buyer.',worker:'Releases expired holds and reconciles stuck payments.'},
   optional:{cdn:'Static assets and periodic seat-map snapshots.',queue:'Feeds the background workers.',lb:'Behind the waiting room.'},whyNot:{},tradeoffs:'Users wait in a queue (fairness and stability vs instant access). The seat map may be a few seconds stale; the hold is always checked in the database.'}}]},
{title:'The purchase flow',tab:'Flow',mins:10,blocks:[
 {t:'diagram',title:'Diagram · Hold → pay → confirm',nodes:['client@0,1:Buyer','api@1,1:Booking service','db@2,1:Seats + orders','provider@2,0:Payment provider','worker@1,2:Expiry job'],edges:['client>api','api>db','api>provider','worker>db'],
  steps:[{hi:['client','api','db'],txt:'<code>UPDATE seats SET status=\'held\', holder=?, held_until=now()+10min WHERE id=? AND status=\'available\'</code>. 1 row = you have it; 0 rows = taken.'},{hi:['api','db'],txt:'Create an order (pending) with an idempotency key.'},{hi:['api','provider'],txt:'Charge with that key. A timeout is retried with the same key: no double charge.'},{hi:['api','db'],txt:'On success: seat → sold, order → confirmed, in one transaction.'},{hi:['worker','db'],states:{worker:'ok'},txt:'Every minute, the expiry job releases holds past held_until and reconciles pending orders with the provider.'}]}]},
{title:'Trade-offs and follow-ups',tab:'Follow-ups',mins:10,blocks:[
 {t:'checkpoint',id:'ctk-cp',title:'Interview checkpoint',prompt:'"How do you guarantee two people never get the same seat, even with 150,000 hold attempts per second?"',model:'Shape demand with a waiting room so the database sees a manageable rate; make the hold one atomic conditional update (or a unique constraint on (event, seat) in a holds table); partition by event/section if needed; seat map from cache, decisions from the DB.',followups:[['"Payment succeeded but the confirm write failed."','Reconciliation job checks pending orders with the provider and confirms or refunds.'],['"Why not hold seats in Redis?"','Possible with atomic ops for speed, but the final sale must be durable in the database; keep one source of truth for the never-happen rule.']]},
 {t:'recall',title:'Active recall',items:[['What prevents double booking?','An atomic conditional update (or unique constraint) on the seat.'],['Why a waiting room?','2 M people cannot all buy 50 K seats; admitting them at a controlled rate protects the system and is fair.'],['Why idempotency keys on payment?','Retries after timeouts must not charge twice.'],['What can be eventually consistent?','The seat map display; never the hold or the sale.']]}]}
]});
